### ISSUE TITLE
upsertpermissionasync

### ISSUE THREAD

**Issue by curelom** [Azure/azure-cosmos-dotnet-v3#1604] opened 2020-06-06 02:42 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

When using User.UpsertPermissionAsync on existing permission, it throws out  Conflict error - Resource with specified id, name or unique index already exists

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.
Run user.upsertpermissionasync with an existing permission.

**Expected behavior**
Expected to replace the existing permission with the one being passed in, hence the "Upsert" part of the method name

**Actual behavior**
Provide a description of the actual behavior observed. 
Throws conflict error

**Environment summary**
SDK Version:  3.9.1
OS Version (e.g. Windows, Linux, MacOSX)
Xamarin Android

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment] 2020-06-07 16:39
@curelom there are tests validating [UpsertPermissionAsync](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5d071ea1693a1c784e10d6b71e98f603647b7f1a/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs#L102). Can you please provide a simple console app that reproduce the issue?

**Comment by j82w** [comment] 2020-06-22 13:01
@curelom I'm closing this since there has been response. Please re-open the issues with a sample if there is still an issue.

**Closed by j82w** 2020-06-22 13:01 UTC
