### ISSUE TITLE
Custom serializer breaks query

### ISSUE THREAD

**Issue by kskem** [Azure/azure-cosmos-dotnet-v3#3280] opened 2022-06-21 10:45 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
The options exposed for the built-in serializer are limited only to changing the name. Additional changes requires a custom serializer. However, any modifications in the custom serializer are not used when performing a query, making the option mostly useless.

**To Reproduce**
- Implement a [custom serializer using example code](https://ankitvijay.net/2021/06/20/custom-json-serializer-settings-with-cosmos-db-sdk/).
- Store data
- Try to query the data with expression or LINQ

### Example data:
```csharp
enum CustomerRole {
  Customer,
  Manager
}
record Customer(string Id, string Name, CustomerRole Role);

var results = (await _container.GetItemLinqQueryable<Customer>().Where(x => x.Role == CustomerRole.Customer)).ToList();
```

### Generated document (with custom serializer):
```
{
  "name": "John Doe"
  "role": "Customer",
  "id": "..."
}
```

**Expected behavior**
The generated SQL should follow the settings on the custom serializer, i.e.:
`WHERE c.role == "Customer"`

The `results` variable should contain the customer element.

**Actual behavior**
The generated SQL follows the default serializer and returns wrong name and value, i.e.:
`WHERE c.Role == 0`

The `results` variable is always empty.

**Environment summary**
SDK Version: 3.28
OS Version: any

**Additional context**
An additional problem is that when setting a default serializer as in the example, it is not possible to also set the SerializerOptions, so all queries will fail unless each instantiated query also has specific serializer options set. This happens in the linked example as well, because the naming convention is changed.

This is similar to issues #3207 and #2685.

**Comment by YipingRuan** [comment] 2022-06-30 04:13
Maybe a small fix here will do?

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dfa0b7c28402ad627a6c11ecf245074a117741e8/Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs#L653

**Comment by YipingRuan** [comment] 2022-06-30 04:23
Seems the `Expression` is already using `int` before the `SqlTranslator.TranslateExpression`..
![image](https://user-images.githubusercontent.com/5492274/176592274-ce77384f-39cc-4d27-b480-124e508fd111.png)

**Comment by onionhammer** [comment] 2022-11-29 22:34
@YipingRuan this is confirmed to not work.

**Comment by ealsur** [comment] 2022-11-29 23:29
Would this be related? https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3406

**Comment by onionhammer** [comment] 2022-11-30 16:33
Workaround does work if you place the StringEnumConverter attribute on the enum type, as opposed to the property you're querying on..

Would be great if this used the settings in your CustomJsonSerializer, rather than newtonsoft json properties

**Comment by kskem** [comment] 2022-12-01 12:00
@onionhammer The underlying problem is that the storage serializer/deserializer can be customized, but the query generator relies on a particular serializer (`NewtonSoft.Json`).

This makes the option to use a custom storage serializer useless when used in combination with LINQ. It works fine if you do not want to query the stored data, or write the query string manually.

You are correct that it can be quick-fixed by adding attributes to the persisted class, but this really makes it hard to swap out `NewtonSoft.Json` later and pollutes the persisted class with a dependency on the `NewtonSoft.Json` library.

The correct fix, IMO, is to update the query generator to not use `NewtonSoft.Json` but instead use the custom serializer, so the names and other quirks are synced between the storage and query. 

If someone is playing around in the query generator, it would be **really** nice if there was an option to say `undefined == null` in the query generator, as `undefined` is not a concept that is supported in C#.

**Comment by jackbond** [comment] 2022-12-29 16:58
Has any progress been made on this issue? I see https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3406 was merged on Oct 13, will it be included in the next release?

**Comment by ealsur** [comment] 2023-01-05 16:14
@jackbond Should be included in the next release, yes.

**Comment by ealsur** [comment] 2023-01-05 16:39
@onionhammer I cannot confirm. The question was if a particular PR was going to be included in the next release (Yes). I don't know if that PR addresses this particular Issue. @leminh98 / @adityasa - do we know if the reported Issue might be fixed by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3406?

**Comment by kskem** [comment] 2023-01-06 07:38
@onionhammer From the description and source changes it should be possible to avoid attributes, at least for custom value serialization (enum) and custom property names.

Closed with #3406.

**Comment by Costo** [comment] 2023-08-09 18:05
#3406 was reverted by #3749 because of a regression. This issue should be reopened.

**Comment by jackbond** [comment] 2023-08-09 19:54
At this point, I'm beginning to wonder if anyone other than Scott Guthrie can ensure this bug is resolved. Seriously, what is it going to take??? It's 2023, System.Text.Json has been out FOR YEARS, and the Cosmos team continues to whistle past graveyards and simply acts like there isn't a problem. Here's an idea, publish a completely separate NuGet package that replaces every usage of Newtonsoft with STJ. We don't need custom serializer support, NOBODY DOES. We need System.Text.Json support and we needed it YEARS AGO!!!!

**Comment by onionhammer** [comment] 2023-08-09 20:00
This library definitely has a lot of legacy bloat and weird windows-specific optimizations that realistically nobody uses..

**Closed** 2024-01-05 21:30 UTC
Labels: needs-investigation, QUERY, LINQ

**Comment by Maya-Painter** [comment] 2024-01-05 21:43
Hi all, we've merged what we hope will be a solution to this issue by allowing the custom serializer to be used for LINQ translations. This also unblocks having System.Text.Json attributes applied in LINQ queries.

We plan to release this as part of the next preview package, but I also wanted to take this time to confirm these changes meet your needs before finalizing them as part of our public API.  If you try the changes out, please follow up in the thread if this update addresses your concerns. If it doesn't, please let us know why.

To use your own custom serializer for LINQ translations you must implement `CosmosLinqSerializer` and set it as a custom serializer on the `CosmosClient`. There is a sample of this for serialization with System.Text.Json in CosmosLinqSerializer.cs.
