### ISSUE TITLE
LINQ-constructed document queries ignore Json annotations based on type constraint

### ISSUE THREAD

**Issue by fabianmeyer** [Azure/azure-cosmos-dotnet-v3#482] opened 2019-06-24 13:45 UTC
**Describe the bug**
When using LINQ to create document queries in a generic function with a constraint on the document's type parameter, the query generator ignores annotations on the concrete type. Specifically, the generator ignores Json serialization annotations on the properties, leading to incorrect queries. 

**To Reproduce**

```
using System;
using System.Linq;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
using Newtonsoft.Json;

namespace ConsoleApp
{
    interface ITest
    {
        string Id { get; set; }
    }

    class Test : ITest
    {
        [JsonProperty("id")] 
        public string Id { get; set; }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            var client = new DocumentClient(new Uri("https://test.documents.azure.com:443/"), "");
            InterfaceConstraint<Test>(client);
            ClassConstraint<Test>(client);
        }

        private static void InterfaceConstraint<T>(IDocumentClient client)
        where T :  ITest
        {
            Console.WriteLine($"InterfaceConstraint Query for T = \"{typeof(T)}\": {client.CreateDocumentQuery<T>(new Uri("https://x.y.z")).Select(doc => doc.Id).ToString()}");
        }
        
        private static void ClassConstraint<T>(IDocumentClient client)
            where T :  Test
        {
            Console.WriteLine($"ClassConstraint Query for T = \"{typeof(T)}\": {client.CreateDocumentQuery<T>(new Uri("https://x.y.z")).Select(doc => doc.Id).ToString()}");
        }
    }
}
```

**Expected behavior**

Query generator should consider annotation on `Test` class. Expected output:
```
InterfaceConstraint Query for T = "ConsoleApp.Test": {"query":"SELECT VALUE root[\"id\"] FROM root "}
ClassConstraint Query for T = "ConsoleApp.Test": {"query":"SELECT VALUE root[\"id\"] FROM root "}
```

**Actual behavior**

Query generator ignores annotation on `Test` class. Actual output:

```
InterfaceConstraint Query for T = "ConsoleApp.Test": {"query":"SELECT VALUE root[\"Id\"] FROM root "}
ClassConstraint Query for T = "ConsoleApp.Test": {"query":"SELECT VALUE root[\"id\"] FROM root "}
```

**Environment summary**
SDK Version: Microsoft.Azure.WebJobs.Extensions.CosmosDB 3.0.3, .NET Core 2.2
OS Version: Windows 10,

**Comment by j82w** [comment] 2019-06-24 14:51
The examples you provided are for v2 SDK. This seems to be a duplicate of https://github.com/Azure/azure-cosmos-dotnet-v2/issues/700. If it's not a duplicate please create a new issue under the v2 SDK repo.

I believe this is still an issue for v3 SDK, Please create a new issue with a v3 SDK samples.

**Closed by j82w** 2019-06-24 14:51 UTC
Labels: V2-SDK, duplicate
