### ISSUE TITLE
Grant AAD group data plane reader permission does not work

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-cosmos-dotnet-v3#3388] opened 2022-08-17 16:30 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I'm following the doc https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac to grant data reader permission to AAD group, then I use one user principal belonging to the AAD group to read container items, however error happens:
Forbidden (403); Substatus: 5301; ActivityId: 3e1f99ac-458c-43ac-b557-b1eadd77fc4e; Reason: (Request blocked by Auth *** : Request is blocked because principal [****] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac.This could be because the user's group memberships were not present in the AAD token.

**To Reproduce**
First grant aad group data reader permission, then run code below to use credential belonging to the aad group:
```
            CosmosClient client1 = new CosmosClient("https://***.documents.azure.com:443/", new InteractiveBrowserCredential());
            var c1 = client1.GetContainer("Regional", "Infra");
            var ret = c1.ReadItemAsync<InfraDoc>("***", new PartitionKey("lgn-rcp::LegionStamp")).Result;
```

**Expected behavior**

No error happens

**Actual behavior**
Provide a description of the actual behavior observed. 

Error happens

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment] 2022-08-19 15:49
@erich-wang Is the principal Id in the error correct? Is it for an AAD App, user, or a the group?

**Comment by ealsur** [comment] 2022-08-19 15:51
Also `InteractiveBrowserCredential` doesn't look like it would be what you'd do when this code is deployed, right? What is the type of credential the code would use to identify the Group otherwise?

**Comment by erich-wang** [comment] 2022-08-22 14:50
@ealsur, yes, the principal id is correct, it is principal id of my corp account, it is aad user and member of the AAD group. You could simply reproduce by: 
1. You may use your team security group, find its object id from https://ms.portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Overview, then grant data contributor to it using [cli](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#using-the-azure-cli-1)
2.  Then run code below and login with your credential that belongs to the security group mentioned in step 1
```
            CosmosClient client1 = new CosmosClient("https://***.documents.azure.com:443/", new InteractiveBrowserCredential());
            var c1 = client1.GetContainer("Regional", "Infra");
            var ret = c1.ReadItemAsync<InfraDoc>("***", new PartitionKey("lgn-rcp::LegionStamp")).Result;
```

**Comment by ealsur** [comment] 2022-08-22 15:01
This question is outside of the SDK scope, please reach out to Azure Support. The SDK has no involvement in validating the access or configurations, it just sends the token representing the principal (which you validated is correct).

The service team that handles AAD/RBAC should investigate this scenario and confirm if it's supported or if it only supports individual identities.

**Comment by ealsur** [comment] 2022-08-24 16:32
@erich-wang I reached out to the service team, they confirmed that AAD Groups are not yet supported (the work is in progress) and will be available in the near future. I'm closing this issue because it is not related to the SDK.

**Closed by ealsur** 2022-08-24 16:32 UTC
Labels: Non-SDK Question, Azure Active Directory

**Comment by erich-wang** [comment] 2022-08-25 04:02
@ealsur, thanks for follow-up. Based on document from https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#limits, it gives impression that Azure AD group has been supported for identities that belong to < 200 groups.

- Azure AD group resolution is not currently supported for identities that belong to more than 200 groups.

**Comment by ealsur** [comment] 2022-08-25 14:33
@erich-wang Yeah, the documentation seems unclear. Please feel free to send feedback on that page (at the bottom) so the team working on AAD can update it/polish it.
