### ISSUE TITLE
Optionally enable/disable AllowBulkExecution dynamically

### ISSUE THREAD

**Issue by mywyb2** [Azure/azure-cosmos-dotnet-v3#1845] opened 2020-09-14 12:42 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, the property ``AllowBulkExecution`` has to be set manually, depending on whether bulk execution is wanted or not. Bulk execution is not only useful for large batch operations, but also for large numbers of incoming parallel single requests.

**Describe the solution you'd like**
An autopilot feature that enables/disables bulk execution dynamically depending on the incoming request rate to the ``CosmosClient``. The threshold rate should be configurable.

**Describe alternatives you've considered**
Building a wrapper around ``CosmosClient`` that measures the incoming request rate and decides whether or not to use ``AllowBulkExecution``. But it's unclear from the documentation whether it's currently safe to set the flag during operation or whether it would be necessary to keep two instances of ``CosmosClient``, one with and one without bulk execution support.

**Comment by ealsur** [comment] 2021-01-26 16:48
Closing as duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1496

**Closed by ealsur** 2021-01-26 16:48 UTC
