### ISSUE TITLE
Add support for managing Users and Resource Tokens

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#240] opened 2019-05-11 11:32 UTC
**Describe the solution you'd like**
I think DocumentClient . should be made public so that operations such as managing Users and Resource Tokens is accessible.

**Describe alternatives you've considered**
Adding the DocumentDB assembly

**Comment by ealsur** [comment] 2019-05-13 13:26
@fuocor DocumentClient will be dissapearing, your concern is to be able to manage users and resource tokens on the new V3 client?

**Comment by fuocor** [comment] 2019-05-14 21:57
yes...

**Comment by wouterdeman** [comment] 2019-07-18 08:31
We are also blocked in using the new v3 version because we want to make use of the Resource token approach isolating access to a given partition. https://docs.microsoft.com/en-us/azure/cosmos-db/secure-access-to-data#resource-tokens Any update on this topic/feature ?

**Comment by thomaslevesque** [comment] 2019-09-05 15:22
Without this feature, the v3 is basically a regression from v2... I spent hours trying to migrate to the new SDK before realizing it didn't support this.

**Comment by j82w** [comment] 2019-09-05 16:17
@fuocor , @wouterdeman , @thomaslevesque the [PR ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/622)is merged to add user and resource token.

**Closed by j82w** 2019-09-05 16:17 UTC

**Comment by thomaslevesque** [comment] 2019-09-06 07:41
@j82w thanks! Any ETA for the next release?

**Comment by j82w** [comment] 2019-09-06 11:53
We will hopefully do a release next week. It might be longer if we hit any unexpected bugs are found.
