### ISSUE TITLE
[Bug]Validate Gateway Tenant DNS changes impact

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-cosmos-dotnet-v3#3523] opened 2022-10-28 20:12 UTC
Validate Gateway Tenant DNS changes impact

**Comment by ealsur** [comment] 2022-10-28 20:13
Clarification: DNS changes on the Gateway tenant, not the account DNS changes

**Comment by xinlian12** [comment] 2022-10-28 20:15
> Clarification: DNS changes on the Gateway tenant, not the account DNS changes

Thanks Matias, updated the title

**Comment by kirankumarkolli** [comment] 2023-05-08 20:51
Duplicate of #3658

**Closed** 2023-05-08 20:51 UTC
Labels: good first issue, needs-investigation, .NET v3 SDK
