### ISSUE TITLE
JsonPropertyAttribute is ignored in method GetItemLinqQueryable on the container.

### ISSUE THREAD

**Issue by HMoen** [Azure/azure-cosmos-dotnet-v3#2963] opened 2021-12-29 17:11 UTC
**Describe the bug**
Json.NET [JsonPropertyAttribute](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonPropertyAttribute.htm) is ignored in method [GetItemLinqQueryable](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemlinqqueryable?view=azure-dotnet) on the container.

**To Reproduce**
```C#

        public abstract class EntityAbstract : IEntity
        {
            [JsonProperty("id")]
            [JsonPropertyName("id")] // Future move to System.Text.Json
            public string EntityId { get; set; }
        }

```

```C#

        public async Task<int> TestCountAsync(string key, string id, CancellationToken token = default)
        {
            return this.CountAsync(
                            key,
                            entity => entity.EntityId == id,
                            entity => entity.EntityId,
                            token: token);
        }

```

```C#
        public async Task<int> CountAsync<TKey>(
            string partitionKey,
            Expression<Func<TEntity, bool>> predicate,
            Expression<Func<TEntity, TKey>> sorter = null,
            bool sortDescending = false
            CancellationToken token = default)
        {
            var predicates = new List<Expression<Func<TEntity, bool>>> { predicate };
            var orderedQueryable = this.BuildQuery(
                partitionKey,
                predicates,
                sorter,
                sortDescending,
                -1);
            var response = await orderedQueryable.CountAsync(token).ConfigureAwait(false);
            return response.Resource;
        }

        private IOrderedQueryable<TEntity> BuildQuery<TKey>(
            string key,
            IEnumerable<Expression<Func<TEntity, bool>>> predicates,
            Expression<Func<TEntity, TKey>> sorter,
            bool sortDescending,
            int maxItemCount)
        {
            var queryRequestOptions = new QueryRequestOptions { MaxItemCount = maxItemCount };
            if (!string.IsNullOrWhiteSpace(key))
            {
                queryRequestOptions.PartitionKey = new PartitionKey(key);
            }

            var queryable = (IQueryable<TEntity>)this.container.GetItemLinqQueryable<TEntity>(
                requestOptions: queryRequestOptions,
                linqSerializerOptions: this.linqSerializerOptions);
            if (predicates != null)
            {
                queryable = predicates.Aggregate(queryable, (current, predicate) => current.Where(predicate));
            }

            return sortDescending ? queryable.OrderByDescending(sorter) : queryable.OrderBy(sorter);
        }

```

**Expected behavior**
```SQL
SELECT VALUE root FROM root WHERE (root[\"id\"] = \"FindMe\") ORDER BY root[\"id\"] ASC
```
**Actual behavior**
```SQL
SELECT VALUE root FROM root WHERE (root[\"entityId\"] = \"FindMe\") ORDER BY root[\"entityId\"] ASC
```

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.23.0
OS Version: Windows 10 / .NET 6

**Comment by HMoen** [comment] 2022-04-08 13:24
Hello @j82w , actual behavior described above remains in package version 3.26.1. Any updates?

**Comment by j82w** [comment] 2022-04-08 14:16
@timsander1 can you please give an update?

**Comment by rf-0** [comment] 2022-09-30 11:04
Any update on this? Happening in latest SDK version ` <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.30.1" />
`

**Comment by neildsh** [comment] 2023-02-16 23:52
I am closing this as a duplicate of #3697 and keeping the newer issue open

**Closed by neildsh** 2023-02-16 23:52 UTC
Labels: needs-investigation, QUERY, LINQ
