### ISSUE TITLE
CosmosDiagnostics throws ArgumentNullException

### ISSUE THREAD

**Issue by LiDamon** [Azure/azure-cosmos-dotnet-v3#2207] opened 2021-02-10 02:46 UTC
System.ArgumentNullException: Value cannot be null.
Parameter name: diagnostics
   at Microsoft.Azure.Cosmos.ResponseMessage..ctor(HttpStatusCode statusCode, RequestMessage requestMessage, Headers headers, CosmosException cosmosException, CosmosDiagnosticsContext diagnostics)
   at Microsoft.Azure.Cosmos.QueryResponse.CreateSuccess(IReadOnlyList`1 result, Int32 count, Int64 responseLengthBytes, CosmosQueryResponseMessageHeaders responseHeaders, CosmosDiagnosticsContext diagnostics, CosmosSerializationFormatOptions serializationOptions)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Storage.CosmosDB.CosmosIndexDocService.<>c__DisplayClass29_0`1.<<Query>b__0>d.MoveNext() in C:\GitLab-Runner\builds\sJLCEyTR\3\cloud\insights\src\Infrastructure\Storages\Storage.CosmosDB\CosmosIndexDocService.cs:line 735
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Storage.CosmosDB.CosmosIndexDocService.Query[T](FilterDefinition filter, SortDefinition sort, Int32 size, String token) in C:\GitLab-Runner\builds\sJLCEyTR\3\cloud\insights\src\Infrastructure\Storages\Storage.CosmosDB\CosmosIndexDocService.cs:line 735
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: diagnostics
   at Microsoft.Azure.Cosmos.ResponseMessage..ctor(HttpStatusCode statusCode, RequestMessage requestMessage, Headers headers, CosmosException cosmosException, CosmosDiagnosticsContext diagnostics)
   at Microsoft.Azure.Cosmos.QueryResponse.CreateSuccess(IReadOnlyList`1 result, Int32 count, Int64 responseLengthBytes, CosmosQueryResponseMessageHeaders responseHeaders, CosmosDiagnosticsContext diagnostics, CosmosSerializationFormatOptions serializationOptions)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Environment summary
SDK Version:3.16.0
OS Version Windows
.NET Version:4.7.2

**Comment by timsander1** [comment] 2021-02-16 15:05
@bchong95 , could you take a look?

**Comment by bchong95** [comment] 2021-02-16 18:12
This code path does not exist anymore in master. Please see if it still reproduces in 3.17.

**Comment by timsander1** [comment] 2021-02-16 18:19
3.17 has not been released yet (release coming soon), so I'll make a note to check back in a few days

**Comment by j82w** [comment] 2021-03-04 22:43
Closing this since 3.17 is now released.

**Closed by j82w** 2021-03-04 22:43 UTC
Labels: Hotfix, QUERY
