### ISSUE TITLE
Change feed processor not distributing traffic to multiple instances

### ISSUE THREAD

**Issue by jordanchang** [Azure/azure-cosmos-dotnet-v3#4212] opened 2023-12-11 20:43 UTC
**Describe the bug**
I have a CosmosDB collection with 8 physical partitions and a Change Feed Processor running on 6 instances, but only 1 instance receives the change events. The other instances are idle.

**To Reproduce**
1. The following code is deployed to 6 instances.
``` var builder = container.GetChangeFeedProcessorBuilder<dynamic>(processorName: _processorName, onChangesDelegate: _handler.HandleChanges);
        _processor = builder
                        .WithInstanceName(Environment.MachineName)
                        .WithLeaseContainer(leaseContainer)
                        .WithStartTime(DateTime.UtcNow.AddDays(-30))
                        .WithErrorNotification(this.OnError)
                        .Build();
        await _processor.StartAsync();
```
2. Deleted leases container so that the change feed re-starts from the beginning.
3. Confirmed the container has more than 1 physical partition
![Screenshot 2023-12-11 at 10 37 11](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/3304352/0b2ff466-1da2-409d-91f1-f2511e3c5ad2)

**Expected behavior**
Since I have 8 physical partitions, all 6 instances should be processing events.

**Actual behavior**
Only 1 instance is receiving all th events.

**Environment summary**
SDK Version:  3.36.0
OS Version: Linux

**Additional context**
1. Container is set to a max of 5000RU/s and autoscale is enabled.
2. All instances are using the same processorName
3. All instances are using the same lease container with partitionKey set to /id.
4. All instances have a unique instance name (GUID from Kubernetes POD)

**Comment by bartelink** [comment] 2023-12-11 20:55
how many partitions get assigned - that's the first step; confirm that's happening
removing filter criteria and/or reducing the max item count will influence whether there are documents to be delivered
instance name does not matter

**Comment by jordanchang** [comment] 2023-12-11 21:16
Thanks for your prompt reply. Forgive me, I am still new to Cosmos. 

- How do I verify how many partitions are assigned? 
- I'm currently not calling "WithMaxItem(int)" in my builder. Are you suggesting, since I am restarting my change feed from 30 days of past data, one instance is being fed the entire batch?

**Comment by bartelink** [comment] 2023-12-11 21:20
there's a wireup in the fluent config API where you can be notified of assignment

>I'm currently not calling "WithMaxItem(int)" in my builder. 

`WithMaxItems(1)` would reduce the risk of items not coming due to it costing too many RUs to get the data

>Are you suggesting, since I am restarting my change feed from 30 days of past data, one instance is being fed the entire batch?

no, but its possible that all the items are residing in one partition (the hashing algorithm will decide based on the defined partition key)

it's also possible that you dont have anything inside the 30 day window

if you have the consumers count the items, you can confirm they are all delivered...

**Comment by jordanchang** [comment] 2023-12-11 22:22
I added a WithLeaseAcquireNotification() callback and it is not being called by my other instances. I do believe I have enough data, because 1 instance currently takes about 2 days to process 30 days of my data. Not sure if this matters, but I'm testing my changes in a lower-level environment and using Cosmos in Serverless mode. 

I also did confirm that if I kill my 1st instance, my second instance is able to pick up the job and resume processing.

**Comment by bartelink** [comment] 2023-12-11 22:30
The data does not come into play until the lease is acquired
So it's a matter of figuring out why that's failing to happen
I believe there's another generic error notification callback that might be worth wiring up too
Is it possible that the aux container is being overloaded, i.e. if you set up the lease time to be very short and have frequent renewals?

**Comment by jordanchang** [comment] 2023-12-11 23:32
Our process has a WithErrorNotification() callback setup and it did not trigger any errors. We're using default lease interval settings and also using Serverless Cosmos, which means I can't increase my max provisioned RU/s in the lease container.

My colleague and I have reviewed our code for the last 3 days and we suspect there is a bug in the SDK or more likely, an error in the official documentation.

Is there a better way to confirm the number of physical partitions detected by the SDK? I suspect the expected number of leases aren't getting created.

**Comment by jordanchang** [comment] 2023-12-12 00:15
I should also note that each document we have in our container has a unique Partition Key value and we have about 30,000 records. I'm not sure if that causes just 1 physical partition to be created under the covers...

**Comment by bartelink** [comment] 2023-12-12 00:21
> has a unique Partition Key value and we have about 30,000 records

If the partition keys are e.g. guids, they should be evenly distributed across the partitions. Just saying if you had 30K with the same partition key, they would be guaranteed to be in the same physical partition even if yiou had 100 of them.

>Is there a better way to confirm the number of physical partitions detected by the SDK? I suspect the expected number of leases aren't getting created.

There is logging you can turn on, I'm pretty sure

You can also see how many documents are being created per subscriber (processor name) in the `-aux` container

I'd also have a look around the classic metrics dashboard to see if anything seems off.

**Comment by jordanchang** [comment] 2023-12-12 02:46
Thanks Ruben for helping us understand this capability of Cosmos.

Upon further reading up on Cosmos Physical Partitions, it appears the number of Physical Partitions is dependent on RUs and storage size. I couldn't find documentation that states when additional Physical partitions are allocated, but it seems like I will need tens of thousands of RU/s provisioned and over 50gb of data. 

Currently, our PROD cosmos looks like this. From these numbers, are you able to tell if we have multiple physical partitions? Perhaps everything is working as designed and I am not quite understanding how this is scaling behind the scenes.

![Screenshot 2023-12-11 at 16 42 56](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/3304352/78370116-0c09-4179-9c71-4df0810aa030)

Documentation from MS:

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/3304352/85be4d0e-6104-4860-a3c5-7eeb3ce9188b)

**Comment by bartelink** [comment] 2023-12-12 03:06
I know the Metrics(classic) dashboard shows physical partition count but I bet googling will either give you a Powershell command or an az query to find out even quicker

A 10GiB container is very unlikely to have split ever. A DB level-allocated one with 3 containers totalling 20GB would be the same thing.
I am not sure if a serverless one is even allowed to split? 
I thought the limit was 50GB but the above quote tells me its now 100GB or at least for your context
Under normal circumstances it will split proactively when you are within e.g. 20% of the limit if you are inserting rapidly
To force a split (and enable splitting the work), you can temporarily give it more RUs than is allowed (IIRC max one physical partition allows is 10K RU, so if you give it 10100, that will force it)
Splits take time to execute (low minutes normally)
Note that forcing a split is a permanent thing (there is a powershell cmdlet to rejoin them but I;ve never done it), so don't do it just for the heck of it

Example problem is if you allocated 500 RU to a container, then forced it to split, the minimum becomes 800 RU (400 per half). Which means that if you're doing reads from only one partition (say you have a hot key), then you are paying 800RU for 400RU of capacity where you formerly paid 500RU for 500 capacity.

**Comment by ealsur** [comment] 2023-12-12 15:43
1. Look at the leases. There should be 9 documents, one with `.info` (not important), then 8 more (if there are 8 partitions). If you don't see 8 lease documents, then there are not 8 physical partitions.
2. Look at the Owner of the leases, is it all the same?
3. Are you sure all instances are running? 
4. Do all instances have the same processorName, and unique different InstanceName (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-processor?tabs=dotnet#dynamic-scaling), with the same monitored and lease container?
5. Regarding documentation about physical partitions ->https://learn.microsoft.com/en-us/azure/cosmos-db/partitioning-overview#physical-partitions

We have not received any bug reports about equal distribution so far in all these years, in most cases the problem is in one of the above points.

**Comment by jordanchang** [comment] 2023-12-12 18:57
1. Given that I have only 9gb of data in a container and provisioned 400 RU/s, I am leaning towards that I don't have more than 1 physical partition.
2. Only 1 lease and 1 owner. If my 1st instance is killed, the other running instance does indeed pick up the job.
3. Yes, all are running.
4. Yes, same processorName and each have a unique instance name (k8s pod name) 
5. New Metrics shows 8 physical partition for all 10 of my containers, which is highly unlikely since some of my containers are empty. I suspect the new Metrics screen is inaccurate and is the source of my confusion.
   * Furthermore, Old Metrics -> Storage doesn't seem to be working on Serverless Cosmos or maybe I have too little data in my lower-level environments
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/3304352/382207af-9c22-4b27-975c-fdb1313f7063)
   * Old Metrics -> Storage shows I have 1 partition (name = 0) in PROD
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/3304352/e22b505b-3026-4689-80b2-c59ae92d950c)

If my assumptions above (1 and 5) are correct, please go ahead and close my bug report and I can open up a separate ticket to improve documentation/troubleshooting steps around this issue.

**Comment by jordanchang** [comment] 2023-12-12 19:23
Thank you for helping us understand how this works. Appreciate the prompt replies!

**Comment by ealsur** [comment] 2023-12-12 19:51
Will close the issue. Please feel free to ask any follow-up questions if needed.

**Closed by ealsur** 2023-12-12 19:51 UTC
Labels: customer-reported, needs-more-information
