### ISSUE TITLE
3.1.0 now missing from NuGet?

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cosmos-dotnet-v3#666] opened 2019-08-12 05:02 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
3.1.0 of the SDK was released not long ago and we were able to download from NuGet. Unsure when it started, however, at the time of writing today....this release is no longer available on NuGet and only has 3.0.0 versions listed.

**To Reproduce**
![image](https://user-images.githubusercontent.com/4549796/62846271-60504100-bd01-11e9-8713-9fe531240e26.png)

**Expected behavior**
To see the 3.1.0 NuGet package listed

**Actual behavior**
Only able to resolve 3.0.0.x

**Environment summary**
SDK Version: 3.1.0
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by riccardobecker** [comment] 2019-08-12 09:02
Yes, i experienced the same issue. Since the 3.1 seriously changed compared to other versions, this has quiet some impact on our current code base. I wonder what happened here.

**Comment by j82w** [comment] 2019-08-12 11:31
Hi @riccardobecker and @wahyuen,

We unlisted the 3.1.0 nuget because there was several regressions that were breaking users. Main issues are .NET framework project would through PInvoke exception when debugging and CreateContainerIfNotExist would throw saying the partition keys do match when they do. You can look at the changelog for the full list. The fixes took a little longer than we expected. We will hopefully have a 3.1.1 out today as long as we don't hit any more blockers.

**Comment by j82w** [comment] 2019-08-12 18:10
The nuget is published. It should be available once nuget.org finishes indexing it. 

https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.1.1

**Comment by j82w** [comment] 2019-08-12 18:30
I'm closing this issue since 3.1.1 is now available.

**Closed by j82w** 2019-08-12 18:30 UTC
