### ISSUE TITLE
Error when using OrderBy on field with possible NULL value: System.NotSupportedException: Cannot execute cross partition order-by queries on mix types

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-cosmos-dotnet-v3#733] opened 2019-08-23 14:22 UTC
**Describe the bug**
I'm performing this code:
```
var otherItems = _container.GetItemLinqQueryable<CosmosItem>(true)
    .Where(i => i.Type != "Unboxed")
    .OrderBy(i => i.OptionalField3_Sortable);
```
which results in the CosmosDB SQL query: 
`SELECT VALUE root FROM root WHERE (root["Type"] != "Unboxed") ORDER BY root["OptionalField3_Sortable"] ASC`

Unfortunately, this query fails with:

> Unhandled Exception: System.NotSupportedException: Cannot execute cross partition order-by queries on mix types. Consider using IS_STRING/IS_NUMBER to get around this exception. Expect type: Null. Actual type: String. Item value: Microsoft.Azure.Cosmos.Query.OrderByItem.
>    at Microsoft.Azure.Cosmos.Query.ParallelQuery.OrderByConsumeComparer.CheckTypeMatching(IList\`1 items1, IList\`1 items2)
>    at Microsoft.Azure.Cosmos.Query.ParallelQuery.OrderByConsumeComparer.CompareOrderByItems(IList\`1 items1, IList\`1 items2)
>    at Microsoft.Azure.Cosmos.Query.CosmosOrderByItemQueryExecutionContext.OrderByEqualityComparer.Equals(CosmosElement x, CosmosElement y)
>    at Microsoft.Azure.Cosmos.Query.ItemProducer.<MoveNextAsync>d__64.MoveNext()

**Additional context**
My container contains items which have OptionalFIeld3_Sortable be either String values, or `null`.
The container's partition key is set on `Type`

PS: I'm very new at using CosmosDB, so it's very possible I'm doing something wrong here... :)

**Comment by NickSevens** [comment] 2019-08-23 14:29
PS: when running the same query in Azure Portal's data explorer, the query DOES work!

**Comment by j82w** [comment] 2019-08-23 14:46
@bchong95 any ideas?

**Comment by NickSevens** [comment] 2019-08-30 07:02
@j82w @bchong95 the error also seems to occur when having only a single partition (partitionkey is equal for all data created in the container)
Any help would be greatly appreciated!

**Comment by kirankumarkolli** [comment] 2019-08-30 14:28
@j82w can you please follow-up with Brandon offline and update next steps?

**Comment by j82w** [comment] 2019-09-03 14:41
@NickSevens the exception message is pretty clear that IS_STRING needs to be added to the query. The issue is the Linq conversion does not support IS_STRING/IS_NUMBER. We are currently looking into the best way to add support for this.

The reason the query works in the Azure Portal's data explorer is the .NET SDK is more strict on the types to avoid [undefined behavior](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6f610954032d913eef13727669d0b7e0f061116c/Microsoft.Azure.Cosmos/src/Query/OrderByQuery/OrderByConsumeComparer.cs#L203). 

To fix your query use the following:
`SELECT VALUE root FROM root WHERE (root["Type"] != "Unboxed" and IS_STRING(root["Type"])) ORDER BY root["OptionalField3_Sortable"] AS`

**Comment by NickSevens** [comment] 2019-09-03 15:31
That seems unlikely to be honest. The issue does nog occur when sorting on DisplayName for example, which never had a NULL value. The issue happens when sorting on a field which can be NULL only.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: j82w <notifications@github.com>
Verzonden: Tuesday, September 3, 2019 4:41:51 PM
Aan: Azure/azure-cosmos-dotnet-v3 <azure-cosmos-dotnet-v3@noreply.github.com>
CC: Nick Sevens <nick_sevens@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Azure/azure-cosmos-dotnet-v3] Error when using OrderBy on field with possible NULL value: System.NotSupportedException: Cannot execute cross partition order-by queries on mix types (#733)


@NickSevens<https://github.com/NickSevens> the exception message is pretty clear that IS_STRING needs to be added to the query. The issue is the Linq conversion does not support IS_STRING/IS_NUMBER. We are currently looking into the best way to add support for this.

The reason the query works in the Azure Portal's data explorer is the .NET SDK is more strict on the types to avoid undefined behavior<https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6f610954032d913eef13727669d0b7e0f061116c/Microsoft.Azure.Cosmos/src/Query/OrderByQuery/OrderByConsumeComparer.cs#L203>.

To fix your query use the following:
SELECT VALUE root FROM root WHERE (root["Type"] != "Unboxed" and IS_STRING(root["Type"])) ORDER BY root["OptionalField3_Sortable"] AS

**Comment by NickSevens** [comment] 2019-09-03 18:10
@j82w I indeed traced it down to the method you referenced.
To me the main issue is however that it's related to _possible_ NULL values.
If a field contains any NULL value, ordering by that field doesn't work, and the same query using another sort field _does_ work.

**Comment by wahyuen** [comment] 2019-09-05 01:31
I believe we are also hitting this same issue, specifically for queries where we have nullable values (in our case, DateTime? property). We are also seeing inconsistencies depending on if you query with an `OrderBy` vs an `OrderByDescending` call, however, I suspect this might just be an issue in the order in which the comparisons are run.

``` csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Fluent;
using Microsoft.Azure.Cosmos.Linq;
using Newtonsoft.Json;

namespace CosmosOrderTest
{
    public class Program
    {
        public const string LocalConnectionString =
            "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;";

        public static async Task Main(string[] args)
        {
            var cosmosClient = new CosmosClientBuilder(LocalConnectionString).Build();

            try
            {
                var database = await cosmosClient.CreateDatabaseIfNotExistsAsync("testdb");
                var container = await database.Database.DefineContainer("testcontainer", "/id").CreateIfNotExistsAsync();

                await container.Container.CreateItemAsync(new TestObject("1"));
                await container.Container.CreateItemAsync(new TestObject("2", DateTime.Now));
                await container.Container.CreateItemAsync(new TestObject("3"));
                await container.Container.CreateItemAsync(new TestObject("4", DateTime.Now));
                await container.Container.CreateItemAsync(new TestObject("5"));

                var options = new QueryRequestOptions {MaxItemCount = 2};

                // no order by
                var noOrderByQuery = container.Container.GetItemLinqQueryable<TestObject>(false, null, options).ToFeedIterator();

                Console.WriteLine("No Order By Query");

                var items = new List<TestObject>();
                var pagedResults = await noOrderByQuery.ReadNextAsync();

                Console.WriteLine($"{pagedResults.Count} - {pagedResults.ContinuationToken}");

                items.AddRange(pagedResults);

                var continuationToken = pagedResults.ContinuationToken;

                while (continuationToken != null)
                {
                    pagedResults = await container.Container.GetItemLinqQueryable<TestObject>(false, continuationToken, options).ToFeedIterator().ReadNextAsync();

                    Console.WriteLine($"{pagedResults.Count} - {pagedResults.ContinuationToken}");

                    items.AddRange(pagedResults);

                    continuationToken = pagedResults.ContinuationToken;
                }

                Console.WriteLine("Results:");

                foreach (var testObject in items)
                {
                    Console.WriteLine($"{testObject.Id} - {testObject.Timestamp}");
                }

                Console.WriteLine($"Total Count:{items.Count}");
                Console.WriteLine();

                // order by asc
                var orderByAsc = container.Container.GetItemLinqQueryable<TestObject>(false, null, options).OrderBy(x => x.Timestamp).ToFeedIterator();

                Console.WriteLine("Order By Ascending");

                items = new List<TestObject>();
                pagedResults = await orderByAsc.ReadNextAsync();

                Console.WriteLine($"{pagedResults.Count} - {pagedResults.ContinuationToken}");

                items.AddRange(pagedResults);

                continuationToken = pagedResults.ContinuationToken;

                while (continuationToken != null)
                {
                    pagedResults = await container.Container.GetItemLinqQueryable<TestObject>(false, continuationToken, options).OrderBy(x => x.Timestamp).ToFeedIterator().ReadNextAsync();

                    Console.WriteLine($"{pagedResults.Count} - {pagedResults.ContinuationToken}");

                    items.AddRange(pagedResults);

                    continuationToken = pagedResults.ContinuationToken;
                }

                Console.WriteLine("Results:");

                foreach (var testObject in items)
                {
                    Console.WriteLine($"{testObject.Id} - {testObject.Timestamp}");
                }

                Console.WriteLine($"Total Count:{items.Count}");
                Console.WriteLine();

                // order by desc
                var orderByDesc = container.Container.GetItemLinqQueryable<TestObject>(false, null, options).OrderByDescending(x => x.Timestamp).ToFeedIterator();

                Console.WriteLine("Order By Descending");

                items = new List<TestObject>();
                pagedResults = await orderByDesc.ReadNextAsync();

                Console.WriteLine($"{pagedResults.Count} - {pagedResults.ContinuationToken}");

                items.AddRange(pagedResults);

                continuationToken = pagedResults.ContinuationToken;

                while (continuationToken != null)
                {
                    pagedResults = await container.Container.GetItemLinqQueryable<TestObject>(false, continuationToken, options).OrderByDescending(x => x.Timestamp).ToFeedIterator().ReadNextAsync();

                    Console.WriteLine($"{pagedResults.Count} - {pagedResults.ContinuationToken}");

                    items.AddRange(pagedResults);

                    continuationToken = pagedResults.ContinuationToken;
                }

                Console.WriteLine("Results:");

                foreach (var testObject in items)
                {
                    Console.WriteLine($"{testObject.Id} - {testObject.Timestamp}");
                }

                Console.WriteLine($"Total Count:{items.Count}");
                Console.WriteLine();

            }
            finally
            {
                var database = cosmosClient.GetDatabase("testdb");
                await database.DeleteAsync();
            }

            Console.WriteLine("Done!");
        }
    }

    public class TestObject
    {
        public TestObject()
        {
        }

        public TestObject(string id, DateTime? timestamp = null)
        {
            Id = id;
            Timestamp = timestamp;
        }

        [JsonProperty("id")]
        public string Id { get; set; }
        [JsonProperty("timestamp")]
        public DateTime? Timestamp { get; set; }
    }
}

```

Yielding a result of:
![image](https://user-images.githubusercontent.com/4549796/64304691-657e7400-cfbf-11e9-84b6-f8b506a47754.png)


Note that in the `OrderBy` scenario, we seem to only obtain the values where the value IS `null`, and receive no values where they are not.

In the case of `OrderByDescending` we get no values and are simply returned the above mentioned exception of: 
```
System.NotSupportedException: 'Cannot execute cross partition order-by queries on mix types. Consider using IS_STRING/IS_NUMBER to get around this exception. Expect type: String. Actual type: Null. Item value: Microsoft.Azure.Cosmos.Query.OrderByItem.'
```

Given the following statement from [ORDER BY clause in Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-order-by)

> ASC | DESC

> Specifies that the values in the specified column should be sorted in ascending or descending order. ASC sorts from the lowest value to highest value. DESC sorts from highest value to lowest value. ASC is the default sort order. Null values are treated as the lowest possible values.

have I made the wrong assumption that we should expect that an `OrderBy` should return `null` values first then non null values?

**Comment by NickSevens** [comment] 2019-09-23 09:48
@j82w revisiting this issue, I keep wondering why I keep receiving the error mentioned above.
The issue occurs because the types `null` and `string` for example do not match, which doesn't make much sense to me... I believe this is a common use-case to order by a nullable field.
Also, the error mentions a **cross-partition** query, but even when passing the `PartitionKey` in the `QueryRequestOptions`, the same error occurs. I believe there at least should be a check on that part then?
Hope you can help me figure this one out...
Thanks in advance.

**Comment by j82w** [comment] 2019-09-23 14:05
@bchong95 can you take a look?

**Comment by MrMint** [comment] 2019-09-30 19:35
With both the portals data explorer and docs leading us to believe sorting nullable strings was possible, we built out a sorting feature and have run into this same issue in the V2 client. Any plans to resolve this issue in V3?

**Comment by wahyuen** [comment] 2019-10-31 01:33
Looks like still an issue in the v3.3.3. 

Is there any indication this might be looked at in the short/near term future? We are at a stage where we are looking at relatively large workarounds to arbitrarily populate `null` fields with a value just so sorting works and would like to assess if its worth us investing the time for this or not.

**Comment by bchong95** [comment] 2019-10-31 02:50
The fix is in this PR: #952

**Comment by wahyuen** [comment] 2019-11-05 00:28
@bchong95 Just tested this on v3.4.0 which should have #952 in it....unfortunately I still think this is an issue?

Ran the same code as above...while it now does not exception out, it still seems to remove results from the result set depending on the order of items. Please see screenshot below where we expect to always return 5 results...but in test case 2 it seems to have only returned the `undefined` values and not the ones with the `DateTime` values.

![image](https://user-images.githubusercontent.com/4549796/68169128-01b7fd80-ffa6-11e9-9e09-247e0bf6a1e2.png)

**Comment by bchong95** [comment] 2019-11-05 21:41
If you are draining through continuation tokens then you are going to face issues with any form of mixed type ORDER BY (UNDEFINED and STRING in this case). This because ORDER BY undefined is defined but range filters on undefined are not. The backend will need to support key set continuation tokens for this to happen, which is further out. 

You add IS_DEFINED to your filter to work around this.

**Closed** 2019-11-17 06:45 UTC
Labels: LINQ, QUERY

**Comment by wahyuen** [comment] 2019-11-17 07:44
@bchong95 is there another ticket to track the work you mentioned regarding the range filters? this is still going to cause anyone who requires filtering on nullable columns with any sort of pagination to implement arbitrary work arounds (setting default values). Simply filtering out values without a value defined isn't really a viable solution for us (and one might assume other customers) given they have modelled the data as being `nullable` in the first place.

**Comment by bchong95** [comment] 2021-01-05 20:51
@wahyuen You can track this PR which adds the fix for continuation token support on ORDER BY undefined:

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2103

**Comment by Luckymaster** [comment] 2024-01-23 16:23
This issue is still not fixed and I am facing this issue. I am using Java SDJ version 4.51.0
