### ISSUE TITLE
SDK allows insertion of items with '/' in id, but does not allow delete

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#2573] opened 2021-06-22 17:51 UTC
I am in the midst of a migration where 1 record out of 900 had a '/' in the identifier, it seems like the import process worked fine using the SDK, but then I can't actually look at the record via Cosmos Data Explorer or delete the item when I want to try to replace the item without the '/'.

**Comment by ealsur** [comment] 2021-06-22 19:10
Hi @onionhammer, this is currently an issue mostly on the fact that the service does not reject invalid characters. SDK does not apply any validation because it is not possible in all scenarios.

If you provide a Stream calling the Stream APIs for example, you are in control of that Stream content.

Any validation should be enforced on the service.

**Comment by onionhammer** [comment] 2021-06-22 21:02
@ealsur So the service selectively enforces that restriction.. makes sense, is there a way to file a bug at the service?

Is there a way to delete an item with an invalid id without deleting the whole container?

**Comment by FabianMeiswinkel** [comment] 2021-06-22 21:24
This link has sample code for how to delete the document: https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-not-found

**Comment by ealsur** [comment] 2021-06-22 22:44
> @ealsur So the service selectively enforces that restriction.. makes sense, is there a way to file a bug at the service?
> 
> Is there a way to delete an item with an invalid id without deleting the whole container?

The service is not applying any validation.

The problem is that your Read request fails because the URL the NodeJS SDK the Portal uses to fetch the item has the Id in it, and that is why it is broken. REST API specification of the service says you can read an item doing a GET to the `/dbs/<yourdb>/colls/<yourcollection>/docs/<id>`. And that breaks if the `id` contains any URL unsafe characters. So the request does not hit the backend with the value you intended, hence the 404.

Apparently, that is documented here: https://docs.microsoft.com/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet#remarks

I am only aware of UserVoice as the place to issue service requests: https://feedback.azure.com/forums/263030-azure-cosmos-db

**Comment by onionhammer** [comment] 2021-06-22 22:52
Interesting.. couldnt the {id} component be url encoded by the SDK?

**Comment by ealsur** [comment] 2021-06-22 23:02
That would mean the REST contract would need to change and REST consumers would also need to escape the ids and the service cannot tell when it is encoded and when it is not. It's not a matter of the SDK doing it or not, it's a matter of, that should have been the design from the start, adding it now I don't believe it's possible.
In any case, it is something that should be driven by the service REST API.

**Comment by ealsur** [comment] 2021-06-22 23:05
Btw, this issue is a duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1908

**Closed** 2021-06-23 00:40 UTC
Labels: Non-SDK Question

**Comment by onionhammer** [comment] 2021-06-23 00:44
I can't see how it wouldn't be possible to return a bad request if an invalid id is being inserted (by the service, not the sdk) but I'll just accept it

**Comment by ealsur** [comment] 2021-06-23 14:23
True, I don't say it's not possible. The service could add a validation and reject any document with an `id` value that has those characters. That would be the ideal solution to this problem because users can save documents through any means that call the REST API (official SDKs, a REST request, custom built SDKs by third-parties), so adding the check on the SDK is not practical and would not solve the problem because it does not cover all the ways documents can be inserted.

**Comment by onionhammer** [comment] 2021-06-23 16:05
@ealsur @FabianMeiswinkel Does this sample not work if the partition key path is /id ?

https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-not-found

**Comment by onionhammer** [comment] 2021-06-23 17:37
OK, here's a workaround for any future user who comes across this; deleting items with invalid IDs appears to be a major pain in the ass, the only way I was able to do it was by invoking the API using the http client:


```C#
string GenerateMasterKeyAuthorizationSignature(string verb, string resourceId, string resourceType, string pk, string key, string keyType, string tokenVersion)
{
    var hmacSha256 = new System.Security.Cryptography.HMACSHA256 { Key = Convert.FromBase64String(key) };

    string payLoad = string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}\n{1}\n{2}\n{3}\n{4}\n",
            verb.ToLowerInvariant(),
            resourceType.ToLowerInvariant(),
            resourceId,
            utc_date.ToLowerInvariant(),
            pk
    );

    byte[] hashPayLoad = hmacSha256.ComputeHash(System.Text.Encoding.UTF8.GetBytes(payLoad));
    string signature = Convert.ToBase64String(hashPayLoad);

    return System.Web.HttpUtility.UrlEncode(String.Format(System.Globalization.CultureInfo.InvariantCulture, "type={0}&ver={1}&sig={2}",
        keyType,
        tokenVersion,
        signature));
}


var client = new System.Net.Http.HttpClient();

utc_date = DateTime.UtcNow.ToString("r").ToLowerInvariant();

//EXECUTE delete
var docId = "VE8FAKg1aiLWAAAAAAAAAA==".ToLowerInvariant(); // _rid in the document you want to delete
var verb = "delete";
var resourceType = "docs";
var resourceLink = "dbs/VE8FAA==/colls/VE8FAKg1aiI=/docs/VE8FAKg1aiLWAAAAAAAAAA==/"; // _self in the document you want to delete
var resourceId =  docId;
var pk = "your-documents-pk";

var authHeader = GenerateMasterKeyAuthorizationSignature(
    verb, resourceId, resourceType, "", cosmosKey, "master", "1.0");

client.DefaultRequestHeaders.Add("x-ms-date", utc_date);
client.DefaultRequestHeaders.Add("x-ms-version", "2018-12-31");
client.DefaultRequestHeaders.Add("authorization", authHeader);
client.DefaultRequestHeaders.Add("x-ms-documentdb-partitionkey", JsonConvert.SerializeObject(new [] { pk }));

var path = new Uri(baseUri: new ("https://your-cosmos-account.documents.azure.com:443"), relativeUri: resourceLink);
var response = await client.DeleteAsync(path);
await response.Content.ReadAsStringAsync()
```
