### ISSUE TITLE
LINQ queries in v3.32 still using Newtonsoft

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#3694] opened 2023-02-07 15:20 UTC
**Describe the bug**
If you have an entity class which looks like this...

```
public class Draw
{
    [JsonProperty(PropertyName = "createdOnFoo")]
    public DateTimeOffset CreatedOn { get; set; }
}
```

And you've defined a custom serializer, the LINQ query, when translated to SQL will look something like...

SELECT TOP 1 VALUE root FROM root WHERE root["createdOnFoo"] > "2023-02-07T15:04:14.6839662+00:00"

And if you get rid of the [JsonProperty] attribute, it will be 

SELECT TOP 1 VALUE root FROM root WHERE root["CreatedOn"] > "2023-02-07T15:04:14.6839662+00:00"

even if your custom serializer specifies camel casing.

**To Reproduce**
See above.

**Expected behavior**
The translation from LINQ to SQL is not using the custom serializer to determine property names.

**Actual behavior**
The translation from LINQ to SQL should use the custom serializer to determine property names.

**Environment summary**
SDK Version:
OS Version Windows

**Comment by neildsh** [comment] 2023-03-06 17:39
Duplicate of #2685. Keeping the older issue open and closing this one.

**Closed by neildsh** 2023-03-06 17:39 UTC
Labels: needs-investigation, QUERY, LINQ
