### ISSUE TITLE
Add client option to use the System.Text.Json Serializer instead of Newtonsoft ...

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-cosmos-dotnet-v3#4540] opened 2024-06-11 01:30 UTC
When creating a Cosmos DB client, allow an option that will use the System.Text.Json serializer instead of Newtonsoft.

As per the StackOverflow question: [https://stackoverflow.com/questions/78604777/why-is-azure-cosmosdb-saving-dictionary-object-values-as-valuekind-number](https://stackoverflow.com/questions/78604777/why-is-azure-cosmosdb-saving-dictionary-object-values-as-valuekind-number).

Instead of incorporating code as per the answer given in the question above, provide a client option that automatically uses the System.Text.Json serializer, for example, an option such as:

UseSystemTextJson = true

When the option is true, the "Serializer" can be set internally using the code from: [https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson)

This simple change would allow us to use the System.Text.Json serializer with the Cosmos SDK (v3) without having to manually incorporate the code above.

Thank-you for your consideration.

**Comment by bartelink** [comment] 2024-06-11 05:54
See #4330 (I basically asked for this in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4325)

**Comment by Pilchie** [comment] 2024-06-11 15:13
Duplicate of #4330

**Closed by Pilchie** 2024-06-11 15:13 UTC
Labels: needs-investigation, customer-reported
