### ISSUE TITLE
Conversion error: ToString CosmosDb SQL  function should be used

### ISSUE THREAD

**Issue by cazac9** [Azure/azure-cosmos-dotnet-v3#3346] opened 2022-07-14 15:22 UTC
**Describe the bug**
This is simplified example
I have a next document structure: 

{"paymentData": {"paymentSummary": {"total": 77}}}

and corresponding c# class

public class PaymentDocument 
{
	[JsonProperty("paymentData")]
	public JToken ExtraData { get; set; }
}
I have a simple code:

_container.GetItemLinqQueryable<PaymentDocument>().Where(t => t.ExtraData["paymentSummary"]["total"].ToString().Contains(request.TotalAmount))

Where: total - number type in json, request.TotalAmount - string

**Expected behavior**
SELECT VALUE root FROM root WHERE CONTAINS(toString(root["paymentData"]["paymentSummary"]["total"]), "7") 

**Actual behavior**
SELECT VALUE root FROM root WHERE CONTAINS(root["paymentData"]["paymentSummary"]["total"], "7")

**Comment by neildsh** [comment] 2022-07-20 23:12
Thank you for raising this issue @cazac9 . This issue has been accepted and is assigned to a  dev to be fixed.

**Closed** 2022-10-13 21:53 UTC
Labels: bug, QUERY, LINQ

**Comment by flamewave** [comment] 2022-10-19 15:26
@neildsh  Just curious, is it known when is this fix expected to be released? I currently have several issues in our system that are caused by this, and managers are wanting to know when this can be fixed. If it's going to be awhile then I'll probably have to figure out a work-around for it.

**Comment by ealsur** [comment] 2022-10-19 16:22
@flamewave We normally have a release cadence of 1-2 weeks

**Comment by jake4e** [comment] 2022-12-21 15:08
@neildsh @ealsur Any update on a release for this?
