### ISSUE TITLE
CosmosClient hang up when run under Orleans

### ISSUE THREAD

**Issue by jkonecki** [Azure/azure-cosmos-dotnet-v3#758] opened 2019-09-01 12:01 UTC
I believe there is a problem with async programming / task scheduler in SDK 3.0. 
The same issue has been reported for SDK 2.0: https://github.com/Azure/azure-cosmos-dotnet-v2/issues/77

When running inside [Microsoft Orleans](http://dotnet.github.io/orleans/) grain, calls to Cosmos DB classes hung. The symptoms are of a tasks deadlock.

The solution is to wrap every call in `Task.Run(() =>{ ... } );`

**To Reproduce**
[Repro.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/3563429/Repro.zip)

Attached is a repro solution. Please edit startup projects for the solution, and set both _OrleansClient_ and _SiloHost_ as Start. 
Please make sure you have a local emulator running, or change connection string in line 20 in _SiloHost.Program.cs_.

The sample will create a Database and Container, and call a grain that will attempt to issue a query using my library (https://github.com/Eveneum/Eveneum). The sample will hung on line 43 in _HelloWorld.Grain.HelloGrain_.

Workaround is to chnage the code to:
`var stream = await Task.Run(() => this.EventStore.ReadStream(this.StreamId));`

**Expected behavior**
Cosmos SDK works correctly with any task scheduler and doesn't deadlock.

**Environment summary**
SDK Version: 3.1.1
OS Version: Windows 1903, .NET Core 2.1.

**Comment by ReubenBond** [comment] 2019-09-03 21:53
This may be a duplicate of #717.

I took a look at the memdump which Jakub sent me & I believe this should be simple to fix.

There is a blocking wait in [AsyncCache here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/76e76dd5f51bdae84927bc3490e2b7903982c38a/Microsoft.Azure.Cosmos/src/Routing/AsyncCache.cs#L52) which is causing a deadlock because it's executing on a single-threaded scheduler and blocking on a task which it enqueues onto that same scheduler (behind itself).

The simple fix would be to create an (AsyncLazy constructor overload](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c7336449207a8315019e8c3772bdf63467a8a3a4/Microsoft.Azure.Cosmos/src/Routing/AsyncLazy.cs#L15) which accepts a `T` instead of `Func<T>` and initializes its base with `Task.FromResult(T)` (i.e, not scheduling a new task).

A more complex fix may involve a change to AsyncCache to not block on the task.

**Comment by jkonecki** [comment] 2019-09-03 21:58
Thanks you, @ReubenBond , very much for your investigation!

Cosmos Team, would you like me to work on the PR?

**Closed** 2019-09-05 16:42 UTC
