### ISSUE TITLE
The client does not attempt to read from other regions

### ISSUE THREAD

**Issue by skurik** [Azure/azure-cosmos-dotnet-v3#1902] opened 2020-10-05 08:57 UTC
**Describe the bug**
The client does not attempt to read from another region.

**To Reproduce**
The issue is intermittent, it manifests when the primary (write) region is unavailable.

**Expected behavior**
The client automatically tries reading from another available region.

**Actual behavior**
We use __GetItemLinqQueryable__. The client is configured as follows:

```
var clientBuilder = new CosmosClientBuilder($"AccountEndpoint={host};AccountKey={accountKey}")
    .WithSerializerOptions(new CosmosSerializationOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase })
    .WithThrottlingRetryOptions(maxRetryWaitTimeOnThrottledRequests.ToTimeSpan(), maxRetryAttemptsOnThrottledRequests);

return clientBuilder.Build();
```

We originally had just one region in West Europe and couple of days ago added a read-only region in North Europe. We did not change the client configuration in any way. 

The problem is that we still occasionally get these errors when querying items:

```
Response status code does not indicate success: ServiceUnavailable (503); Substatus: 0; ActivityId: 61ec3016-6990-4816-87f7-19d08d5b3e2f; Reason: (The request failed because the client was unable to establish connections to 3 endpoints across 1 regions. The client CPU was overloaded during the attempted request.)
```

Why doesn't it attempt to reach the second region? Or am I misreading the error message?

**Environment summary**
SDK Version: 3.9.11
OS Version: Windows App Service in Azure

**Comment by ealsur** [comment] 2020-10-05 14:58
ServiceUnavailable are retried once on an alternate region only if ApplicationPreferredRegions has 2 or more preferred regions, on SDKs > 3.12.0:

![image](https://user-images.githubusercontent.com/1633401/95095671-2f3e8700-06e0-11eb-8b02-cde4e8756051.png)

Reference: https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-sdk-availability#transient-connectivity-issues-on-tcp-protocol

![image](https://user-images.githubusercontent.com/1633401/95095772-55642700-06e0-11eb-98bf-ca6c4781b31c.png)

In your case though, your CPU is overloaded, meaning that you have resource starvation, so even if the SDK retried, there are high chances it might not succeed, since your CPU usage would still be high. 

The recommendation is to investigate your application and understand what happens when you have CPU spikes, something in your app logic is driving the CPU up the roof.

**Comment by ealsur** [comment] 2020-10-05 21:20
Closed as expected behavior. SDK configuration does not have multiple PreferredRegions.

**Closed by ealsur** 2020-10-05 21:20 UTC

**Comment by skurik** [comment] 2020-10-06 11:45
@ealsur What if I don't specify any preferred region, but I set the __ApplicationRegion__ property? Wouldn't it then make sense to also retry on transient network issues, trying to reach the next nearest available region?

**Comment by ealsur** [comment] 2020-10-06 14:59
If you use [ApplicationRegion](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.applicationregion?view=azure-dotnet), then the preferred regions is built based on the distance of your account's regions to the region you specified. 
For example, if your account is in East US, South Central US, and Europe, and you set ApplicationRegion to South Central US, the preferred regions would be populated as: South Central US, East US, and Europe.

Since the preferred regions is populated and has more than 1 value, then the retry on 503 would happen.

**Comment by skurik** [comment] 2020-10-06 15:22
Great, I was wondering if __ApplicationRegion__ reduces to __PreferredRegions__ behind the scenes. Thanks @ealsur!
