### ISSUE TITLE
Transport and Gone Exceptions are occurring continuously

### ISSUE THREAD

**Issue by chetankashetti** [Azure/azure-cosmos-dotnet-v3#2111] opened 2021-01-10 13:25 UTC
**Describe the bug**
I have 2 issues.
1. TransportExceptions are logged around 15 mins every day at the same time from the past seven days. at this moment we have analyzed our logs, the CPU and RU usage is under 30%. no problems with resource utilization. Is this because of IdleTcpConnectionTimeout (24 hours) ? since it's occurring every 24 hours
2. GoneExceptions are occurring consistently without any pattern. during this time we don't see any major resource usage. CPU and RU usage are under 40%. we are going clueless about what's going wrong in the system. 

have a couple of questions
1. Do we lose any document during these exceptions? for example while running createItemAsync if any of these two exceptions occurs, will the item be created? or it won't? 
2. According to docs retry logic works on throttled requests, does the logic work for these exceptions?
before logging these exceptions does it retry and then it will log an exception?

**To Reproduce**
we are unable to repro this issue.

**Expected behavior**
Those exceptions shouldn't occur. 

**Actual behavior**
Exceptions are getting logged continuously. 

**Environment summary**
SDK Version: 3.9.1
OS Version: Windows 10
Cosmos Direct mode TCP connection with IdleTCPConnectionTimeout of 24 hours.
we have a single cosmos client.
outbound ports enabled from 10000-20000
we are running our app in the k8s environment. 

**TransportException**
TransportException: A client transport error occurred: Acquiring the send stream lock timed out. 
{"Order":10,"Line":0,"ColumnSpecified":false,"Method":"Boolean CreateItem[T](System.String, T)","FileName":null,"ILOffsetSpecified":false,"NativeOffset":390,"NativeOffsetSpecified":true},{"Order":11,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},
{"Order":12,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},{"Order":13,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Cosmos.ContainerCore+<CreateItemAsync>d__56`1","FileName":null,"ILOffsetSpecified":false,"NativeOffset":547,"NativeOffsetSpecified":true},
{"Order":14,"Line":0,"ColumnSpecified":false,"Method":"T ProcessMessage[T](Microsoft.Azure.Cosmos.ResponseMessage, System.Func`2[Microsoft.Azure.Cosmos.ResponseMessage,T])","ClassName":"Microsoft.Azure.Cosmos.CosmosResponseFactoryCore","FileName":null,"ILOffset":9,"ILOffsetSpecified":true,"NativeOffset":46,"NativeOffsetSpecified":true},
{"Order":15,"Line":0,"ColumnSpecified":false,"Method":"Microsoft.Azure.Cosmos.ResponseMessage EnsureSuccessStatusCode()","ClassName":"Microsoft.Azure.Cosmos.ResponseMessage","FileName":null,"ILOffset":8,"ILOffsetSpecified":true,"NativeOffset":50,"NativeOffsetSpecified":true}]
{"Order":16,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.Rntbd.TransportClient+<InvokeStoreAsync>d__10","FileName":null,"ILOffset":287,"ILOffsetSpecified":true,"NativeOffset":558,"NativeOffsetSpecified":true}
{"Order":17,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},
{"Order":18,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},
{"Order":19,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.Rntbd.LoadBalancingPartition+<RequestAsync>d__9","FileName":null,"ILOffset":341,"ILOffsetSpecified":true,"NativeOffset":751,"NativeOffsetSpecified":true},
{"Order":20,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},
{"Order":21,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},
{"Order":22,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.Rntbd.Channel+<RequestAsync>d__13","FileName":null,"ILOffset":828,"ILOffsetSpecified":true,"NativeOffset":2083,"NativeOffsetSpecified":true}],"DateTime":"2021-01-06T02:37:19.0527932Z","NumberSpecified":false,"Message":"TransportException: A client transport error occurred: Acquiring the send stream lock timed out. 

GoneException:
The requested resource is no longer available at the server.\r\nActivityId: 88c27b3e-2b41-4705-9def-e34f9107316b, Windows/10.0.17763 cosmos-netstandard-sdk/3.9.0
{"Order":7,"Line":0,"ColumnSpecified":false,"Method":"System.Collections.Generic.List`1[T] GetQueryResults[T](Microsoft.Azure.Cosmos.FeedIterator`1[T])","FileName":null,"ILOffsetSpecified":false,"NativeOffset":185,"NativeOffsetSpecified":true},{"Order":8,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},{"Order":9,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},{"Order":10,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Cosmos.FeedIteratorCore`1+<ReadNextAsync>d__6","FileName":null,"ILOffset":131,"ILOffsetSpecified":true,"NativeOffset":324,"NativeOffsetSpecified":true},{"Order":11,"Line":0,"ColumnSpecified":false,"Method":"Microsoft.Azure.Cosmos.ReadFeedResponse`1[TInput] CreateResponse[TInput](Microsoft.Azure.Cosmos.ResponseMessage, Microsoft.Azure.Cosmos.CosmosSerializerCore)","ClassName":"Microsoft.Azure.Cosmos.ReadFeedResponse`1","FileName":null,"ILOffset":22,"ILOffsetSpecified":true,"NativeOffset":82,"NativeOffsetSpecified":true},{"Order":12,"Line":0,"ColumnSpecified":false,"Method":"Microsoft.Azure.Cosmos.ResponseMessage EnsureSuccessStatusCode()","ClassName":"Microsoft.Azure.Cosmos.ResponseMessage","FileName":null,"ILOffset":8,"ILOffsetSpecified":true,"NativeOffset":50,"NativeOffsetSpecified":true}{"Order":13,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.RequestRetryUtility+<ProcessRequestAsync>d__2`2","FileName":null,"ILOffsetSpecified":false,"NativeOffset":480,"NativeOffsetSpecified":true},{"Order":14,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},{"Order":15,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},{"Order":16,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.ReplicatedResourceClient+<>c__DisplayClass27_0+<<InvokeAsync>b__0>d","FileName":null,"ILOffset":391,"ILOffsetSpecified":true,"NativeOffset":730,"NativeOffsetSpecified":true},{"Order":17,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},{"Order":18,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},{"Order":19,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.ConsistencyReader+<ReadSessionAsync>d__13","FileName":null,"ILOffset":148,"ILOffsetSpecified":true,"NativeOffset":300,"NativeOffsetSpecified":true},{"Order":20,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},{"Order":21,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},{"Order":22,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.StoreReader+<ReadMultipleReplicaAsync>d__11","FileName":null,"ILOffset":212,"ILOffsetSpecified":true,"NativeOffset":417,"NativeOffsetSpecified":true},{"Order":23,"Line":0,"ColumnSpecified":false,"Method":"Void HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)","ClassName":"System.Runtime.CompilerServices.TaskAwaiter","FileName":null,"ILOffset":40,"ILOffsetSpecified":true,"NativeOffset":60,"NativeOffsetSpecified":true},{"Order":24,"Line":0,"ColumnSpecified":false,"Method":"Void Throw()","ClassName":"System.Runtime.ExceptionServices.ExceptionDispatchInfo","FileName":null,"ILOffset":12,"ILOffsetSpecified":true,"NativeOffset":31,"NativeOffsetSpecified":true},{"Order":25,"Line":0,"ColumnSpecified":false,"Method":"Void MoveNext()","ClassName":"Microsoft.Azure.Documents.StoreReader+<ReadMultipleReplicasInternalAsync>d__13","FileName":null,"ILOffset":613,"ILOffsetSpecified":true,"NativeOffset":1047,"NativeOffsetSpecified":true},{"Order":26,"Line":0,"ColumnSpecified":false,"Method":"Void ThrowGoneIfElapsed()","ClassName":"Microsoft.Azure.Documents.TimeoutHelper","FileName":null,"ILOffset":33,"ILOffsetSpecified":true,"NativeOffset":134,"NativeOffsetSpecified":true}],"DateTime":"2021-01-06T15:30:40.0656602Z","NumberSpecified":false,"Message":"GoneException: The requested resource is no longer available at the server.\r\nActivityId: 88c27b3e-2b41-4705-9def-e34f9107316b, Windows/10.0.17763 cosmos-netstandard-sdk/3.9.0","Source":"Microsoft.Azure.Cosmos.Direct","Command":null,"Depth":3}

**Comment by j82w** [comment] 2021-01-11 12:37
@chetankashetti can you please provide the full exception `ToString()` which includes the [CosmosDiagnostics](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0e338b7cc683290de4e978080ad457a2bcd7c7b9/Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs#L122)?

**Comment by chetankashetti** [comment] 2021-01-17 15:40
@j82w  Thank you for the response.
I will be upgrading to the above-mentioned version. unfortunately, we're not logging cosmosDiagnostics. we're planning to do it.

With Direct mode adding retries to transient exceptions that cause 503, 410, 408. there will definitely be a performance impact? since we're adding the retry count as 3. it'll block the thread for completing those counts. 

If there's any performance impact what would be the difference between Gateway vs Direct in numbers?
for example suppose gateway is taking 100ms to complete operation, however Direct in 60 ms.

If the margin is minimal, This will help us to know whether to switch back to Gateway. since Direct is giving some issues.

**Comment by ealsur** [comment] 2021-02-10 00:01
@chetankashetti Gateway mode has no SLAs backing latency so normally Direct is always more performant, see https://docs.microsoft.com/en-us/azure/cosmos-db/sql-sdk-connection-modes.

Closing, please reopen if more information is available for troubleshooting

**Closed by ealsur** 2021-02-10 00:01 UTC
Labels: needs-investigation

**Comment by orgiele** [comment] 2021-12-03 15:40
@ealsur would you be willing to reopen the issue if I provide you with a 17MB cosmos diagnostics file? I have it exported from my company's ApplicationInsights. Here I can attach the anonymised file, stripped of our production database name. However, I can also send you a full file via email since my company has a bilateral NDA with Microsoft.
Best regards

**Comment by ealsur** [comment] 2021-12-03 17:15
@orgiele Not sure I understand, is your case exactly like the OP? If you are running into Diagnostics with TransportExceptions, I recommend to go through the guides to troubleshoot the cause: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-dot-net-sdk-request-timeout?tabs=cpu-new#troubleshooting-steps

**Comment by orgiele** [comment] 2021-12-04 06:35
We have the same problem as the one described by the OP:
>GoneExceptions are occurring consistently without any pattern. during this time we don't see any major resource usage. CPU and RU usage are under 40%. we are going clueless about what's going wrong in the system.

We've already opened the azure support ticket and tried to troubleshoot it on our end (no results yet). For now, the only suspicious finding we have is that `GoneExceptions` occur only on one AKS node at a time (each time on a different node).\
Regarding the troubleshooting, no logged request has the `isThreadStarving` flag set to true. Only 70 requests out of almost 6000 from the AppIns dump have CPU>70%. \
I'll check the "SNAT exhaustion" lead with our DevOps team.

**Comment by orgiele** [comment] 2021-12-06 09:17
Our engineers confirmed that SNAT exhaustion did not take place when these issues occurred.

**Comment by ealsur** [comment] 2021-12-06 17:40
Please open a different Issue in this case and share there all the diagnostics information, these type of problems are case-by-case and depends entirely on the client environment.
Also the support case will take a look at other things (like issues on the Cosmos DB backend) unrelated to the SDK that could also cause this.
