### ISSUE TITLE
.NET 6 DateOnly Property Not Deserialized Correctly

### ISSUE THREAD

**Issue by RichMercer** [Azure/azure-cosmos-dotnet-v3#2908] opened 2021-11-25 09:56 UTC
**Describe the bug**

When using `container.ReadItemAsync<T>()` to fetch an object with a DateOnly property, the property has a value of 01/01/0001. Looking a the document directly in Data Explorer the property is serialized as follow:

```
"testDateOnly": {
    "year": 2020,
    "month": 5,
    "day": 30,
    "dayOfWeek": 6,
    "dayOfYear": 151,
    "dayNumber": 737574
}
```

It seems it's unable to deserialize this property correctly when fetching.

**To Reproduce**

```
    public class TestClass
    {
        public string Id { get; set; }
        public DateOnly TestDateOnly { get; set; }
    }

    public async Task TestDateOnlyAsync()
    {
        var testClass = new TestClass { Id = "d99ee405c09d46d2bdc68c84f2a47acb", TestDateOnly = new DateOnly(2020, 05, 30) };

        await container.UpsertItemAsync(testClass, new PartitionKey(testClass.Id), new ItemRequestOptions { EnableContentResponseOnWrite = false });

        var fetchedEntity = await container.ReadItemAsync<TestClass>("d99ee405c09d46d2bdc68c84f2a47acb", new PartitionKey("d99ee405c09d46d2bdc68c84f2a47acb"));

        Console.WriteLine(fetchedEntity.Resource.TestDateOnly);
    }
```

**Expected behavior**
Expected output: 30/05/2020

**Actual behavior**
Actual output: 01/01/0001

**Environment summary**
SDK Version: v3.23.0
OS Version: macOS Monterey

**Comment by jackbond** [comment] 2021-11-27 17:20
Removing Cosmos from the picture, you'll see the same behavior.

```
DateOnly expected = new DateOnly(2021, 10, 8);

string json= JsonConvert.SerializeObject(dateOnly);

DateOnly actual = JsonConvert.DeserializeObject<DateOnly>(json);
```
Ultimately the issue is NewtonSoft isn't properly handling DateOnly. Your best bet is to create your own custom serializer for DateOnly.

https://github.com/JamesNK/Newtonsoft.Json/issues/2521

**Comment by RichMercer** [comment] 2021-11-28 19:57
Yeah, it seems the same issue exists with System.Text.Json and ultimately it's because .NET 6 shipped without serialization support for DateOnly and TimeOnly. I guess this isn't an issue that can be fixed within the Cosmos SDK.

https://github.com/dotnet/runtime/issues/53539#issuecomment-962674409

**Comment by j82w** [comment] 2021-11-29 13:46
Closing this issue since this problem is not caused by Cosmos DB SDK.

**Closed by j82w** 2021-11-29 13:46 UTC
