### ISSUE TITLE
GetChangeFeedProcessorBuilder is inaccessible due to its protection level

### ISSUE THREAD

**Issue by adriancuadrado** [Azure/azure-cosmos-dotnet-v3#3053] opened 2022-02-27 19:09 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
The compiler complains that the method "GetChangeFeedProcessorBuilder" is inaccessible in Azure.Cosmos version 4 preview 3.

**To Reproduce**
1. `dotnet add package Azure.Cosmos --version 4.0.0-preview3`
2. 
```csharp
CosmosClient cosmosClient = new CosmosClient(EndpointUrl, AuthorizationKey);
container.GetChangeFeedProcessorBuilder<object>(processorName: "changeFeedSample", onChangesDelegate: HandleChangesAsync)
  .WithInstanceName("consoleHost")
  .WithLeaseContainer(leaseContainer)
  .Build();
```

**Expected behavior**
Either the compiler should not complain or the docs should mention which method to use in the latest version.

**Actual behavior**
The compiler doesn't let the code be compiled.

**Environment summary**
SDK Version: Azure.Cosmos 4.0.0-preview3
.Net Version: 6.0.101
OS Version: Windows 10 (Ubuntu 20.04 LTS using WSL)

**Additional context**
N/A

**Comment by bartelink** [comment] 2022-02-27 20:53
If you look around at other open and/or recent issues, you'll see that the V4 work on that branch is very stale and there is no presently valid V4 code that you should be basing anything on. I'd suggest revising the question in terms of the V3 API.

**Comment by adriancuadrado** [comment] 2022-02-27 23:36
> If you look around at other open and/or recent issues, you'll see that the V4 work on that branch is very stale and there is no presently valid V4 code that you should be basing anything on. I'd suggest revising the question in terms of the V3 API.

I know. There is a reason why the V4 is still in preview. Still, I thought it would be helpful to report this problem.

**Comment by bartelink** [comment] 2022-02-27 23:45
>Still, I thought it would be helpful to report this problem.

Far more useful to clarify whether the problem you cite exists on V3 (and/or what you are proposing; it's not obvious to me from the OP) - the next V4 type thing will be based off master in this repo in order to take in all the features and fixes in the two years since then.

**Comment by ealsur** [comment] 2022-03-01 15:09
As @bartelink pointed out, this is not an error. V4 SDK is a spike, not intended for production usage and does not include all the features V3 has. It does not have Change Feed Processor.

**Comment by ealsur** [comment] 2022-03-01 15:12
Latest version is always referring to the latest stable, unless it's a preview feature on which we call out which preview version can be used. V4 release notes also call out that it is not meant for production usage:  https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/README.md#microsoft-azure-cosmos-db-net-sdk-version-4, https://docs.microsoft.com/en-us/azure/cosmos-db/sql/create-sql-api-dotnet-v4.

**Comment by bartelink** [comment] 2022-03-01 16:28
>Maybe I expressed myself wrong.

Closing the issue is the clearest signal of intent ;P (Don't worry, nobody is inferring bad intent on your part, but when we are separated by a common language, being explicit is the best way to avoid confusion)

>that V4 wouldn't work in some scenarios

For avoidance of doubt, it's a really bad idea to use this V4 for anything of any kind _except to understand the approximate degree of client API churn that following the `Azure.Core` conventions will trigger_ - there's been years of feature development and bugfixes.

**Closed** 2022-03-01 16:31 UTC
