### ISSUE TITLE
Querying a database with a large offset allocates a lot more memory than expected on the client.

### ISSUE THREAD

**Issue by SebastianVeile** [Azure/azure-cosmos-dotnet-v3#3597] opened 2022-12-07 09:37 UTC
**Describe the bug**
When querying a database with a large offset, the client allocates a lot more memory than expected.

**To Reproduce**
Run a query with a large offset on a Cosmos database with more than 100k entries. Use the code snippet below

**Expected behavior**
I would expect the database to process the rows which are to be skipped due to the OFFSET/SKIP part of the query in the database, not sending them to the client at all. Thus I would expect the query to be slow and potentially very expensive for the database, but not expensive in terms of client memory.

**Actual behavior**
When skipping every item in a database with 350k entries it allocates around 685 MBs. Which is a lot more memory than I would expect the client to deal with.  Since the query skips all entries and return an empty result, i would expect the memory to be much much lower.

**Environment summary**
SDK Version: 3.31.2
TargetFramework: .Net 6.0
LanguageVersion: 10
OS Version: Windows 10

Here is the code to reproduce, with generation of dummy items to query.
DummyItem is a repositoryitem that contains a date value and a dummy value
The code will prompt you for the amount to generate, the account endpoint and your key.
I recommend generating at least 100k in one run and then doing a second run where you do not generate anything to best gauge the memory usage of the query itself.
```csharp
using AutoFixture;
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace MInimal_reproducable_example_cosmos
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("Input the number of entries to generate");
            var count = int.Parse(Console.ReadLine());
            Console.WriteLine("Input Account endpoint");
            var accountEndpoint = Console.ReadLine();
            Console.WriteLine("Input AuthKey");
            var autkey = Console.ReadLine();
            using CosmosClient client = new CosmosClient(
                accountEndpoint: accountEndpoint,
                authKeyOrResourceToken: autkey
            );

            var container = client.GetContainer("BusinessIntelligenceService", "BusinessIntelligenceService");

            var newItems = new List<DummyItem>();
            for (int i = 0; i < count; i++)
            {
                DummyItem item = new DummyItem();
                newItems.Add(item);
            }
            var upsertTasks = newItems.Select(item => container.UpsertItemAsync(item));
            var bulkTask = Task.WhenAll(upsertTasks);
            await bulkTask;
            Console.WriteLine("Done inserting");

            var itemCount = (await container.GetItemLinqQueryable<DummyItem>().Where(item => item.dummy == "dummyvalue").CountAsync()).Resource;
            Console.WriteLine("Number of items total: " + itemCount);
            var items = container.GetItemLinqQueryable<DummyItem>();
            var query = items
                .Where(item => item.TimeStamp > DateTime.MinValue)
                .OrderBy(x => x.TimeStamp)
                .Skip(itemCount + 1)
                .Take(1);
            var sqlQuery = query.ToString();
            Console.WriteLine("Query:" + sqlQuery);
            var stream = query.ToStreamIterator();
            var result = (await stream.ReadNextAsync()).Content;
            Console.WriteLine("Done");
            stream.Dispose();
            Console.ReadLine();
        }
    }
}
```

**Comment by ealsur** [comment] 2022-12-12 11:29
@neildsh / @jcocchi Can anyone help with this query related question about how OFFSET/LIMIT works?

**Comment by neildsh** [comment] 2022-12-12 18:18
Hello @SebastianVeile, are these cross partition queries ?

**Comment by SebastianVeile** [comment] 2022-12-13 08:22
> Hello @SebastianVeile, are these cross partition queries ?

Yes, that is the case for this query

**Comment by jnysteen** [comment] 2023-01-12 11:50
I'm also affected by this behaviour

**Comment by Maya-Painter** [comment] 2024-05-03 17:38
@SebastianVeile @jnysteen If these are cross-partition queries this behavior is expected.  In the cross-partition case, queries with `OFFSET X LIMIT y` are rewritten as `LIMIT x + y` before being sent to the backend partitions. See Query vs RewrittenQuery tags in https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.OffsetLimit.xml for examples of OFFSET LIMIT rewrites.

The OFFSET LIMIT logic is applied on the client side after retrieving the documents, since there is no guarantee about how many will be retrieved from each partition.

**Comment by Maya-Painter** [comment] 2024-05-07 23:16
Closing issue as by design

**Closed by Maya-Painter** 2024-05-07 23:16 UTC
Labels: QUERY
