### ISSUE TITLE
System.ArgumentException thrown when calling CreateDatabaseIfNotExistAsync with CosmosClientOption configured with ConsistentPrefix consistency

### ISSUE THREAD

**Issue by IshamMohamed** [Azure/azure-cosmos-dotnet-v3#2196] opened 2021-02-08 11:59 UTC
The problem exists in: https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.16.0 (the latest version of v3 client) and does not exist in https://www.nuget.org/packages/Azure.Cosmos/4.0.0-preview3 (latest v4 preview client)

**Describe the bug**
A cosmosdb instance was created in SouthEastAsia region with "Session" default consistency. The following C# code was used to create a DB if not exist:
```
CosmosClientOptions cosmosClientOptions = new CosmosClientOptions
{
    ConsistencyLevel = ConsistencyLevel.ConsistentPrefix
};
CosmosClient cosmosClient = new CosmosClient(CosmosEndpointUrl, AuthKey, cosmosClientOptions);

DatabaseResponse databaseResponse = await cosmosClient.CreateDatabaseIfNotExistsAsync(DatabaseId);
```

This throws a `System.ArgumentException` saying `"Consistency level Bounded Staleness specified in the request is invalid when service is configured with consistency level Session"`. This error it self is wrong as **Bounded Staleness was not mentioned** in the code. If `ConsistencyLevel  = ConsistencyLevel.Eventual` is used in the `cosmosClientOptions ` there error does not appear.

**To Reproduce**
1) Create a cosmos db instance with `Session` default consistency level
2) Try to create a database in the cosmosdb instance via a code similar to the above - an exception will be thrown. 

**Expected behavior**
There should not be any error if the cosmos client if instantiated with a weaker consistency than the default constituency defined in the cosmosdb instance. 

**Actual behavior**
A misleading exception is being thrown.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.16.0
Framework: .NET Core 3.1
OS Version: Windows 10 20H2 19042.746

**Additional context**
https://pbs.twimg.com/media/EtmPEIJU0AMtqvA?format=png&name=large

**Comment by j82w** [comment] 2021-02-08 13:19
@IshamMohamed I was able to reproduce this. It seems to not show up when testing against the local emulator.

**Comment by j82w** [comment] 2021-02-08 13:34
@IshamMohamed I found the bug. It's incorrectly converting the consistency levels. I'll send out a fix. This seems to have existed since 3.1.0. The fix will be released in the next few weeks. 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/776af4be89a6ececda78f5454c40fda95336e9db/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L723

**Comment by IshamMohamed** [comment] 2021-02-08 13:36
Great!

**Closed** 2021-02-08 19:35 UTC
Labels: Hotfix, bug, has-repro

**Comment by j82w** [comment] 2021-02-15 20:15
@IshamMohamed please try the 3.17.0-preview release
