### ISSUE TITLE
Preserve some of the way creating a query worked in v2

### ISSUE THREAD

**Issue by crhistianramirez** [Azure/azure-cosmos-dotnet-v3#26] opened 2019-01-24 19:40 UTC
I liked how [CreateDocumentQuery](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.createdocumentquery?view=azure-dotnet) worked in v2. It returned an `IQueryable` so you could have one function that built up part of the query and pass it on to some other function that added to that query before executing it. It also let us use linq methods to build up the query.

Was it removed for performance reasons? Is there any way to retain some of the spirit of how it worked?

**Comment by kirankumarkolli** [comment] 2019-01-30 17:02
@crhistianramirez we are exploring ways of enabling LINQ query generation. Its part of GA plan.

**Comment by j82w** [comment] 2019-05-30 12:03
Closing this since it's a duplicate of #212

**Closed by j82w** 2019-05-30 12:03 UTC
Labels: discussion-wanted, duplicate
