### ISSUE TITLE
Excessive FeedIterator looping

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#2229] opened 2021-02-18 00:12 UTC
**Describe the bug**
A query that takes 1 round trip to execute at https://cosmos.azure.com/ is taking 16 round trips when using the Microsoft.Azure.Cosmos NuGet library. The database I am running this against has Read and Write Locations in North Central US 
and South Central US.

**To Reproduce**
Solution attached.

**Expected behavior**
1 round trip.

**Actual behavior**
16 round trips.

**Environment summary**
SDK Version: 3.16.0 for sure, but goes back further.
OS Version: Windows.

[SdkIssue.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/5999348/SdkIssue.zip)

**Comment by j82w** [comment] 2021-02-18 01:25
@timsander1 or @bchong95 can you please take a look?

**Comment by bchong95** [comment] 2021-02-18 17:18
Hi @jackbond 

We were able to reproduce your issue. In the more recent SDKs versions we added more preemption points in the query iteration logic. The FeedIterator yields a page of result for every page it gets from the service. Before we used to batch these pages as much as possible for the caller and return a single large page. This led to two issues. The first is that the query was less responsive, since the caller would have to await for results from all partitions before getting a single page back. The second is that if the FeedIterator retrieved a page from the backend that wouldn't fit in the caller's specified maxItemCount, then it would throw away the result essentially wasting RUs. 

If the concern is the number of roundtrips from your middle tier to your application layer, then you can batch pages manually in the middle to optimize for this. Some psuedoish code would be:

```
List<Item> items = new List<Item>();
int middleTierPageSize = 100;
string continuationToken = null;
FeedIterator<Item> feedIterator = CreateFeedIterator(continuationToken, middleTierPageSize);
while (feedIterator.HasMoreResults && items.Count != middleTierPageSize)
{
        FeedResponse<Item> page = feedIterator.ReadNextAsync();
        int roomLeftInPage = middleTierPageSize - items.Count;
        if(page.Count > roomLeftInPage)
        {
               // We grabbed too many results for the batching of pages
               feedIterator = CreateFeedIterator(continuationToken, roomLeftInPage);
               page = feedIterator.ReadNextAsync();
        }
        
        items.AddRange(page);
        continuationToken = page.ContinuationToken;
}

return (items, continuationToken);
```

Please let us know if you have any other concerns.

**Comment by jackbond** [comment] 2021-02-18 22:16
Hi @bchong95

Thank you for your quick response. Something seems VERY WRONG here. Setting aside potential workarounds for a second, when I run one of my queries locally, it's taking 10 seconds to return 11 documents from a collection with 966 total documents. I think a lot of people would be surprised for that to be the default behavior from the code below. I'm also not sure what you mean by "from your middle tier to your application tier". To make it really concrete, my concern is how many round trips it takes from my application code to Cosmos. I've included the debug output I'm seeing below. Is it normal to be seeing this many connections and handshakes operations? As I said earlier, this same query in the portal takes about 2 seconds.

```
            using FeedIterator<DocumentWrapper<T>> iterator =  query.ToFeedIterator();

            string queryText = query.ToQueryDefinition().QueryText;

            DateTimeOffset startTime = DateTimeOffset.UtcNow;

            Debug.WriteLine($"QueryText: {queryText}");

            while (iterator.HasMoreResults)
            {
                FeedResponse<DocumentWrapper<T>> items = await iterator.ReadNextAsync(cancellationToken).ConfigureAwait(false);

                totalCharge += items.RequestCharge;
                roundTrips++;

                result.AddRange(items.Select(z => z.Document));
            }

            Debug.WriteLine($"Duration: {DateTimeOffset.UtcNow - startTime}");            
            Debug.WriteLine($"Roundtrips: {roundTrips}");
```

QueryText: SELECT VALUE root FROM root WHERE (((root["deletedOn"] = null) OR (NOT IS_DEFINED(root["deletedOn"]))) AND ((root["label"] = "SampleDocument") AND (ARRAY_LENGTH(root["document"]["items"]) > 2)))
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14094/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14094/apps/8c4bc221-6e30-4a7a-b066-532e6f758bbf/services/1b5dc0d4-e24a-49f0-8efa-c05dba0a408c/partitions/8d392908-47d9-4456-a779-f827ca97568e/replicas/132454938164596948s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14094/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14094/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61524 -> 65.52.210.9:14094
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61524 -> 65.52.210.9:14094
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14118/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14118/apps/2c855c97-f894-4f78-b82e-7d2da642b013/services/3d19529b-c89d-4081-b6b9-5042305cf676/partitions/b8b859b2-742b-4534-8e3b-54306a056bfe/replicas/132455244324372032s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14118/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14118/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61525 -> 65.52.210.9:14118
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61525 -> 65.52.210.9:14118
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14345/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14345/apps/8c4bc221-6e30-4a7a-b066-532e6f758bbf/services/a2018b46-d587-406f-9589-5485ab937fb4/partitions/9a905070-6452-4223-855e-4c511777b189/replicas/132449295631809176s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14345/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14345/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61527 -> 65.52.210.9:14345
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61527 -> 65.52.210.9:14345
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14078/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14078/apps/8c4bc221-6e30-4a7a-b066-532e6f758bbf/services/a7f852ef-063b-4ef0-b7a3-8a60d76530f4/partitions/6f88c6a4-190e-4d83-804f-f73d1a8a511d/replicas/132554496817986890s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14078/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14078/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61528 -> 65.52.210.9:14078
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61528 -> 65.52.210.9:14078
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14104/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14104/apps/2c855c97-f894-4f78-b82e-7d2da642b013/services/bcfe1d18-396e-4b08-8881-275609f3cca4/partitions/c08d916d-f23f-43f0-acbe-fb8526c60bf1/replicas/132576306466603955s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14104/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14104/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61529 -> 65.52.210.9:14104
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61529 -> 65.52.210.9:14104
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14378/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14378/apps/2c855c97-f894-4f78-b82e-7d2da642b013/services/6ccb25c5-a368-4edf-ad28-1787afacd9fe/partitions/5169f631-5d3b-46f9-aba6-bfe3499f1281/replicas/132488686519934568s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14378/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14378/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61530 -> 65.52.210.9:14378
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61530 -> 65.52.210.9:14378
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14387/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14387/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14387/apps/2c855c97-f894-4f78-b82e-7d2da642b013/services/d458f27c-ab83-43ad-a356-70fe1e59f0e0/partitions/da6a0c56-d287-470c-9da4-669ebf89ebf1/replicas/132572926655511494s/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14387/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61531 -> 65.52.210.9:14387
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61531 -> 65.52.210.9:14387
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14386/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14386/apps/8c4bc221-6e30-4a7a-b066-532e6f758bbf/services/bd14d3a8-e0ae-43bd-bd6a-f629e0aefe74/partitions/58265910-7584-484b-93c1-3e21f6284477/replicas/132470244707743200p/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14386/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd2.documents.azure.com:14386/ (address 65.52.210.9)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61532 -> 65.52.210.9:14386
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61532 -> 65.52.210.9:14386
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14302/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14302/apps/75156c2e-1811-4881-834d-262db7d6e6f3/services/6614d59a-1090-41c4-ab3f-d8c76602319d/partitions/57abc04b-6632-4405-a6ba-589e2adad60c/replicas/132555781465838632s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14302/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14302/ (address 52.162.106.10)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61533 -> 52.162.106.10:14302
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61533 -> 52.162.106.10:14302
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14335/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14335/apps/75156c2e-1811-4881-834d-262db7d6e6f3/services/afe228a6-d3d6-450e-b537-0d5ade9747af/partitions/27e09018-8860-49d0-803a-32c5df874ae2/replicas/132560426677020402s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14335/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd7.documents.azure.com:14335/ (address 52.162.106.10)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61534 -> 52.162.106.10:14335
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61534 -> 52.162.106.10:14335
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14198/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14198/apps/ec38ea0b-bcae-4fd9-8cab-15dc46e5cec0/services/47b03172-b344-413f-9e3f-cf187fdeb52a/partitions/ee8a7892-2a9b-474e-9320-c0bb22757aeb/replicas/132552294819203683p/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14198/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14198/ (address 23.96.219.207)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61537 -> 23.96.219.207:14198
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61537 -> 23.96.219.207:14198
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14386/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14386/apps/ec38ea0b-bcae-4fd9-8cab-15dc46e5cec0/services/4b0a67c9-88da-40fb-8715-3ce797ce22fd/partitions/b519eb6c-44e4-410d-86a3-0b8c9b6fa39f/replicas/132551522949775568p/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14386/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14386/ (address 23.96.219.207)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61538 -> 23.96.219.207:14386
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61538 -> 23.96.219.207:14386
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14393/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14393/apps/e76e515e-a556-4c72-bee2-85eae0a7fad3/services/805c6bf0-6909-4d1f-9c37-0d06959a9377/partitions/88020475-21d9-4c0d-9a5b-25350711fc8b/replicas/132563073861760504s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14393/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14393/ (address 23.96.219.207)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61539 -> 23.96.219.207:14393
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61539 -> 23.96.219.207:14393
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14348/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14348/apps/e76e515e-a556-4c72-bee2-85eae0a7fad3/services/9dac0443-6f52-46df-a9d6-56ed7430a125/partitions/156fcbb2-16e8-42a1-8499-1093b57d03cb/replicas/132531128349323697s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14348/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd3.documents.azure.com:14348/ (address 23.96.219.207)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61540 -> 23.96.219.207:14348
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61540 -> 23.96.219.207:14348
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14312/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14312/apps/8c91a418-c1cf-4beb-a4b8-73c0abb39bb4/services/fb18ee42-e9ed-4a22-8b3d-cfd227685d37/partitions/15d9a085-818c-4483-86e7-294ca019b30f/replicas/132580038854488399s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14312/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14312/ (address 52.162.252.26)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61541 -> 52.162.252.26:14312
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61541 -> 52.162.252.26:14312
DocDBTrace Information: 0 : Opened 1 channels to server rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14326/
DocDBTrace Information: 0 : Awaiting RNTBD channel initialization. Request URI: rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14326/apps/8c91a418-c1cf-4beb-a4b8-73c0abb39bb4/services/ea5c28a7-1f27-4db6-bcd7-43e2c52c15f5/partitions/8b9ebead-9248-43de-8b23-b500f846b3a2/replicas/132570006778202098s/
DocDBTrace Information: 0 : Port reuse mode: ReuseUnicastPort. Connection: <not connected> -> rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14326/
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-northcentralus1-fd1.documents.azure.com:14326/ (address 52.162.252.26)
DocDBTrace Information: 0 : RNTBD connection established 192.168.1.7:61542 -> 52.162.252.26:14326
DocDBTrace Information: 0 : RNTBD SSL handshake complete 192.168.1.7:61542 -> 52.162.252.26:14326
Duration: 00:00:13.4751403
Roundtrips: 16

**Comment by bchong95** [comment] 2021-02-18 23:54
It's hard to tell where the time is being spent. Can you provided CosmosDiagnostics traces with this nuget package? 

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2172

Or you can wait till SDK 3.17 is out, which has the needed details.

**Comment by jackbond** [comment] 2021-02-19 00:08
Would the 3.17 preview work?

**Comment by bchong95** [comment] 2021-02-19 00:13
Yeah preview works :)

**Comment by jackbond** [comment] 2021-02-19 00:15
I've updated to the preview, the debug output looks pretty much the same. Do I have to change a setting to get additional information?

**Comment by bchong95** [comment] 2021-02-19 00:19
oh make sure you are logging items.CosmosDiagnostics

**Comment by jackbond** [comment] 2021-02-19 00:28
Hopefully you'll be able to make some sense of this... :)

[diagnostics.json.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/6006774/diagnostics.json.txt)

**Comment by bchong95** [comment] 2021-02-19 02:00
From the diagnostics it looks like your client is spend most of the time on the network. Please rerun this on a machine that is collocated with your data and also set the max degree of parallelism + max buffered item count to a high value.

**Comment by jackbond** [comment] 2021-02-19 02:57
Previously I had set {MaxBufferedItemCount = int.MaxValue} and didn't see any change. I just updated QueryRequestOptions to  {MaxConcurrency = 16} and the total duration of the while loop went down to 1.5 seconds, pretty much on par with what I've been seeing when running through the portal. I then changed to {MaxConcurrency = -1} and also saw 1.5 seconds. Am I correct in concluding that not setting MaxConcurrency is equivalent to {MaxConcurrency = 1}?

Upping the concurrency certainly reduces the overall query time, but I'm curious what "round trips" means in the "Query Stats" tab on cosmos.azure.com. I had assumed that number lined up with the number of calls to ReadNextAsync on an iterator. If the number circled on this page is accurate, how are they getting all the results in 1 trip? 

![image](https://user-images.githubusercontent.com/2799232/108449719-c97b1380-7218-11eb-8b41-f8ed4e3ee97e.png)

**Comment by j82w** [comment] 2021-02-19 12:58
@southpolesteve can you help answer the question about query in the portal?

**Comment by southpolesteve** [comment] 2021-02-19 16:01
@jackbond. The portal uses the JavaScript SDK to make queries directly to the service via gateway mode. It also has some special configuration that is designed to provide the best experience for browser users and restrictions of that environment, so it may not exactly match the behavior of another SDK. 

You are correct the round trip count is calculated on the client from how many times the query iterator in the JS SDK call in the browser. In some cases the underlying code will need to make multiple requests in order to complete a query. Round trips here is not necessarily the same thing as request count.

If you have any more questions about the data explorer, feel free to open an issue in our repo https://github.com/Azure/cosmos-explorer

**Comment by j82w** [comment] 2021-03-05 14:44
Closing this since the question has been answered, and there has been no updates. Please feel free to reopen if there is additional questions.

**Closed by j82w** 2021-03-05 14:44 UTC
Labels: QUERY, needs-investigation

**Comment by YohanSciubukgian** [comment] 2021-03-05 15:45
Do you have any documentation or details related to "we added more preemption points in the query iteration logic" ? Does it implies more latency or cost (RU) due to multiple calls done on the background ? Does it have the same behavior on gateway mode and direct mode ? I would like to understand SDK configuration impact. ;)

**Comment by j82w** [comment] 2021-03-05 15:57
@YohanSciubukgian can you please open a new issue for your question.
