### ISSUE TITLE
Queries not working in emulator

### ISSUE THREAD

**Issue by sehcheese** [Azure/azure-cosmos-dotnet-v3#856] opened 2019-09-27 15:02 UTC
**Describe the bug**
When I run the CosmosDb emulator for local development and attempt to query, I get this error when reading results from a query using [`GetItemQueryIterator`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemqueryiterator?view=azure-dotnet)
> Response status code does not indicate success: 400 Substatus: 0 Reason: (Response status code does not indicate success: 400 Substatus: 0 Reason: (Gateway Failed to Retrieve Query Plan: Unknown QueryFeatures:  NonValueAggregateActivityId: f2ee3729-8021-4d23-a656-33a1ab830d92, Microsoft.Azure.Documents.Common/2.5.1, Windows/10.0.18362 cosmos-netstandard-sdk/3.2.1).).

Other methods like `CreateItemAsync` and `ReadItemStreamAsync` work. Furthermore, this error is isolated to the emulator. If I run this code against an Azure CosmosDb, I do not get the error.

**To Reproduce**
I have reproduced this on two machines regularly used for development with CosmosDb. We recently upgraded our .NET Framework project to use Azure Cosmos SDK v3. I was using version 2.4.5 of the emulator, and after upgrading to 2.5.6 (following steps at https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/cosmos-db/local-emulator.md#troubleshooting) the issue persisted. Here is the code that produces the error

```c#
var cosmosDb = await Storage.GetCosmosDb();
var queryDefinition = new QueryDefinition($"SELECT * FROM projects project WHERE project.organization = '{CurrentUser.Organization}'");
var queryRequestOptions = new QueryRequestOptions
{
    PartitionKey = new PartitionKey(CurrentUser.Organization),
};
var projectsQuery = cosmosDb.Containers[typeof(Project)]
    .GetItemQueryIterator<Project>(queryDefinition, null, queryRequestOptions);
var projects = new List<Project>();
while (projectsQuery.HasMoreResults)
{
     projects.AddRange(await projectsQuery.ReadNextAsync());
}
```

**Expected behavior**
The CosmosDb emulator should work for querying locally with `GetItemQueryIterator`.

**Actual behavior**
I get an exception with the error message above.

**Environment summary**
SDK Version: 3.2.0
OS Version; Windows 10 Home 1903

**Additional context**
Here's the stack trace from the route that calls `GetItemQueryIterator`:

```
  at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
  at Microsoft.Azure.Cosmos.CosmosResponseFactory.CreateQueryFeedResponseHelper[T](ResponseMessage cosmosResponseMessage, Boolean usePropertySerializer)
  at Microsoft.Azure.Cosmos.CosmosResponseFactory.CreateQueryFeedResponse[T](ResponseMessage cosmosResponseMessage)
  at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
  at DesignService.Controllers.ProjectController.<GetProjects>d__3.MoveNext() in C:\Users\scott\Documents\Paragon\ParagonCore\servers\DesignService\DesignService\Controllers\ProjectController.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by j82w** [comment] 2019-09-30 14:27
@sehcheese can you please go the emulator icon in the bottom try. Right click and the about and verify you are running against the lastest 2.5.6.0? I just did a quick test with a similar query and completed successfully.

**Comment by j82w** [comment] 2019-09-30 15:25
@bchong95 do you have any ideas on what would cause this?

**Comment by j82w** [comment] 2019-09-30 16:12
@sehcheese are you running the application on windows 64bit?

**Comment by sehcheese** [comment] 2019-09-30 16:17
@j82w I am on Windows 64 bit, and "Azure Cosmos DB Emulator" appears in folder "C:\Program Files", not "C:\Program Files (x86)". Is there a setting somewhere I need to change to target the local dll, or should that happen automatically in the x64 Cosmos DB Emulator?

**Comment by j82w** [comment] 2019-09-30 16:36
It's not about the emulator. It's about the application. Most .NET framework application default targeting to x32 bit, and the service interop dll only works on x64 application running on Windows.

**Comment by j82w** [comment] 2019-09-30 17:12
I was able to get a repo of the issue. I'm still figuring out the root cause. You can switch your application to target x64 to get around the issue for now.
![image](https://user-images.githubusercontent.com/8868107/65899687-18e14b00-e369-11e9-8cdd-14607393e4ea.png)

**Comment by j82w** [comment] 2019-10-01 18:03
@sehcheese I verified that the issue is the client has new feature that the emulator doesn't currently have. We are working on publishing a new emulator that will fix this issue.

**Comment by j82w** [comment] 2019-10-04 11:28
@sehcheese the latest emulator is released with the fix. Please download it and let me know if there is any issues.

**Closed by j82w** 2019-10-04 11:28 UTC
Labels: QUERY, bug
