### ISSUE TITLE
Client initialization fails due to time-out on account read

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#1670] opened 2020-06-26 21:01 UTC
he code that throws the error:

var database = Client.CreateDatabaseIfNotExistsAsync(DatabaseName).ConfigureAwait(false).GetAwaiter().GetResult().Database;
var containerTasks = ContainerDefinitions.Select(c =&gt; database.CreateContainerIfNotExistsAsync(c.Properties));
            Task.WhenAll(containerTasks).ConfigureAwait(false).GetAwaiter().GetResult();

The stack trace:

  'Type':'System.Threading.Tasks.TaskCanceledException',
  'Message':'A task was canceled.','InnerExceptions':[],'StackTrace':[' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Cosmos.ClientExtensions.&lt;GetAsync&gt;d__0.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.&lt;GetMasterAddressesViaGatewayAsync&gt;d__23.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.&lt;ResolveMasterAsync&gt;d__21.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.&lt;TryGetAddressesAsync&gt;d__19.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)',' at Microsoft.Azure.Cosmos.AddressResolver.&lt;ResolveAddressesAndIdentityAsync&gt;d__12.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)',' at Microsoft.Azure.Cosmos.AddressResolver.&lt;ResolveAsync&gt;d__9.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Documents.AddressSelector.&lt;ResolveAddressesAsync&gt;d__5.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Documents.AddressSelector.&lt;ResolveAllUriAsync&gt;d__3.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()',' at Microsoft.Azure.Documents.StoreReader.&lt;ReadMultipleReplicasInternalAsync&gt;d__13.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)',' at Microsoft.Azure.Documents.StoreReader.&lt;ReadMultipleReplicaAsync&gt;d__11.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)',' at Microsoft.Azure.Documents.QuorumReader.&lt;ReadQuorumAsync&gt;d__14.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at Microsoft.Azure.Documents.QuorumReader.&lt;ReadStrongAsync&gt;d__12.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)',' at Microsoft.Azure.Documents.ReplicatedResourceClient.&lt;&gt;c__DisplayClass27_0.&lt;&lt;InvokeAsync&gt;b__0&gt;d.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at Microsoft.Azure.Documents.RequestRetryUtility.&lt;ProcessRequestAsync&gt;d__2`2.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)',' at Microsoft.Azure.Documents.RequestRetryUtility.&lt;ProcessRequestAsync&gt;d__2`2.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Documents.StoreClient.&lt;ProcessMessageAsync&gt;d__19.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at Microsoft.Azure.Documents.ServerStoreModel.&lt;ProcessMessageAsync&gt;d__15.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()',' at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)',' at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)',' at Microsoft.Azure.Cosmos.Handlers.TransportHandler.&lt;ProcessMessageAsync&gt;d__3.MoveNext()','--- End of stack trace from previous location where exception was thrown ---',' at Syste

**Comment by j82w** [comment] 2020-06-30 12:53
@kirankumarkolli I ran the following test several times and didn't see any issues. Do you see something I missed?
```c#
        [TestMethod]
        public void CreateContainerDeadlockTest()
        {
            List<ContainerProperties> containerDefinition = new List<ContainerProperties>()
            {
                new ContainerProperties("test1", "/id"),
                new ContainerProperties("test2", "/id"),
                new ContainerProperties("test3", "/id")
            };

            Cosmos.Database database = this.cosmosClient.CreateDatabaseIfNotExistsAsync(nameof(CreateContainerDeadlockTest)).ConfigureAwait(false).GetAwaiter().GetResult().Database;
            IEnumerable<Task<ContainerResponse>> containerTasks = containerDefinition.Select(c => database.CreateContainerIfNotExistsAsync(c));
            Task.WhenAll(containerTasks).ConfigureAwait(false).GetAwaiter().GetResult();
        }
```

**Comment by j82w** [comment] 2020-06-30 18:21
At further investigation the issue appears to be caused by the [GatewayAddressCache](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/37763a47f24c8d700f6061fdfbf2a0697fc1c352/Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs#L403) does not have any retry logic for even basic http exceptions. 

My current idea on how to fix this is to add a BackOffRetryUtil using the [WebExceptionRetryPolicy](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/WebExceptionRetryPolicy.cs) to the  GatewayAddressCache call.

**Comment by kirankumarkolli** [comment] 2020-07-01 14:02
LGTM

**Comment by j82w** [comment] 2020-07-01 14:22
@ealsur can the PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1548 be merged now? I want to avoid merge conflicts with the changes you are making.

**Comment by ealsur** [comment] 2020-07-01 17:04
Wrapping on that retry policy sounds good

**Comment by j82w** [comment] 2020-09-08 16:39
This is fixed in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1788

**Closed by j82w** 2020-09-08 16:39 UTC
Labels: LiveSite
