### ISSUE TITLE
Verify Database/Container CreateIfNotExists are equal to input

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#545] opened 2019-07-15 19:21 UTC
Create{Database/Container}IfNotExists should throw an exception if the resource being created is different from the existing resource.

**Comment by kirankumarkolli** [comment] 2019-07-15 20:28
Duplicate of #549 with exact specification.

**Closed by kirankumarkolli** 2019-07-15 20:28 UTC
Labels: bug
