### ISSUE TITLE
TransactionalBatch.ExecuteAsync doesn't support retries

### ISSUE THREAD

**Issue by jahmai-ca** [Azure/azure-cosmos-dotnet-v3#1905] opened 2020-10-06 04:21 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

TransactionalBatch cannot be retried in the case of a network error.

**To Reproduce**

Call TransactionalBatch.ExecuteAsync over a flakey network connection. If it fails due to a network error, call TransactionalBatch.ExecuteAsync again, it will throw ArgumentException.

**Expected behavior**

To be able to call ExecuteAsync again until the request reaches the server.

**Actual behavior**

ExecuteAsync throws ArgumentException on retries.

**Environment summary**
SDK Version: 3.9.1
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

I believe it is because the operations list for the batch is being cleared before the batch is actually sent to the server:

See BatchCore.cs:

```
        /// <summary>
        /// Executes the batch at the Azure Cosmos service as an asynchronous operation.
        /// </summary>
        /// <param name="requestOptions">Options that apply to the batch.</param>
        /// <param name="cancellationToken">(Optional) <see cref="CancellationToken"/> representing request cancellation.</param>
        /// <returns>An awaitable <see cref="TransactionalBatchResponse"/> which contains the completion status and results of each operation.</returns>
        public override Task<TransactionalBatchResponse> ExecuteAsync(
            TransactionalBatchRequestOptions requestOptions,
            CancellationToken cancellationToken = default)
        {
            return this.container.ClientContext.OperationHelperAsync(
                nameof(ExecuteAsync),
                requestOptions,
                (diagnostics) =>
                {
                    BatchExecutor executor = new BatchExecutor(
                                    container: this.container,
                                    partitionKey: this.partitionKey,
                                    operations: this.operations,
                                    batchOptions: requestOptions,
                                    diagnosticsContext: diagnostics);

                    this.operations = new List<ItemBatchOperation>(); // !!! This should be cleared after executor.ExecuteAsync completes successfully?
                    return executor.ExecuteAsync(cancellationToken);
                });
        }

```

**Comment by j82w** [comment] 2020-10-06 11:48
@jahmai this is a misunderstanding in the way c# works. The BatchExecutor is getting a pointer to the 'this.operations' list. Then a new list is getting set on the 'BatchCore' class. This means that the BatchCore can not change the list after it is sent to the BatchExecutor. 

The SDK will not retry transient networking connections for write operations. This is because its not possible for the SDK to know if the original request actually succeeded or failed. It's possible that the SDK connected and sent the payload. The Cosmos DB service received the payload and started processing it then the connection was dropped for some reason. The Cosmos DB service will complete the request in this scenario, but there is no way for the SDK to know this. It's also possible that only part of the request made it so it was never completed. If the SDK retries and it succeeded it will create a 409 conflict which some application handle differently than a success. Since there is now way for us to know for sure if the 409 was from the original request succeeding or caused by an existing item it's up to the application developers handle it. This way they can correctly handle the different scenarios.

**Comment by jahmai** [comment] 2020-10-06 22:56
@j82w Thanks, I've been a C# programmer for 12 years so your answer is a little condescending.

I know the SDK doesn't retry failures and I am not asking for that, but the caller can retry on certain types of exceptions if they wish. Since the SDK mutates the batch object during the request (even before it is fully executed), that is impossible.

**Comment by j82w** [comment] 2020-10-06 23:29
I apologize if it came off as condescending. I did not mean for it to be. I misunderstood the problem, and you have a valid issue.

Here are some possible solutions:
1. Use the a custom [RequestHandler](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/67a2c582f510e91afdc9609b3779f06a8e04ec69/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L177) which would allow you to retry on all requests not just batch.
2. Switching it to not replace the list is an option, but it would be a breaking change which would require it to be done the v4 SDK.
3. Expose a new API to get the operations and execute them. Something like `IReadOnlyList<ItemBatchOperation> GetOperations` and `ExecuteAsync(IReadOnlyList<ItemBatchOperation> batchOperations)`. 

Number 3 seems like the best long term fix. @jahmai do you have any feedback or suggestions on the possible solutions?

**Comment by jahmai** [comment] 2020-10-07 04:03
@j82w All good and thanks for following up so quickly.

Either #2 or #3 would be fine to me. I've already worked around the issue by re-creating the entire batch from scratch, which is a little expensive but it should be very rare, but it would be nice to see this handled better in the future.

**Comment by abhijitpai** [comment] 2021-03-28 17:00
@j82w do we need #1911 and this or are they both the same? Am okay with 3 - any suggestions on how to expose OperationType?

**Comment by j82w** [comment] 2021-03-29 11:40
This seems to be a duplicate of 1911. I'm closing it.

**Closed by j82w** 2021-03-29 11:40 UTC
Labels: Batch, customer-reported, feature-request
