### ISSUE TITLE
Renaming Document Id property in .NET Core 3.0 requires Newtonsoft.Json

### ISSUE THREAD

**Issue by DanielLarsenNZ** [Azure/azure-cosmos-dotnet-v3#951] opened 2019-10-31 01:01 UTC
**Describe the bug**
Several Microsoft samples for Cosmos DB and .NET Core use `Newtonsoft.Json.JsonPropertyAttribute` to rename the `Id` property on a model to `id`. In .NET Core and ASP.NET Core, [`Newtonsoft.Json` has been replaced by `System.Text.Json`](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support). If I use `System.Text.Json.Serialization.JsonPropertyNameAttribute` instead, `CosmosClient.CreateItemAsync()` fails with the following error message:

```
The input content is invalid because the required properties - 'id; ' - are missing
```

**To Reproduce**

See my fork of [cosmos-dotnet-core-todo-app](https://github.com/DanielLarsenNZ/cosmos-dotnet-core-todo-app) in which I have followed the steps below:

1. Create, clone or open a Cosmos + .NET Core app
2. Upgrade the app to .NET Core 3.0 (if not already targeted)
3. Remove references to `Newtonsoft.Json`
4. Replace `[Newtonsoft.Json.JsonProperty("id")]` attributes with `[System.Text.Json.Serialization.JsonPropertyName("id")]` attributes.
5. Run the app and create a Document

**Expected behavior**
I expect that the `Id` property will be renamed to `id` by the native `System.Text.Json` attribute and that Cosmos DB will accept the document and create it.

**Actual behavior**

```
CosmosException: Response status code does not indicate success: 400
The input content is invalid because the required properties - 'id; ' - are missing
```

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.3.3
OS Version Windows 10 1909 (OS Build 18363.418)

**Additional info**
Workarounds are 1. use Newtonsoft.Json and 2. rename the property on the model class to "id".

**Comment by DanielLarsenNZ** [comment] 2019-10-31 01:02
See also #202

**Comment by j82w** [comment] 2019-10-31 11:38
This is a goal in the VNext SDK. The current v3 has hard dependencies on Newtonsoft. We also ran into a few blockers trying to do the conversion that the System.Text.Json library should address in the next release.

**Comment by j82w** [comment] 2019-11-04 11:08
I'm closing this as a duplicate of [#202](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/202)

**Closed by j82w** 2019-11-04 11:08 UTC
