### ISSUE TITLE
When `AllowBulkExecution` is true, `ReadItemAsync` and `ReadItemStreamAsync` will never yield `NotModified` on a `IfNoneMatchEtag`, even when it is expected

### ISSUE THREAD

**Issue by nickwb** [Azure/azure-cosmos-dotnet-v3#4195] opened 2023-11-22 04:19 UTC
**Describe the bug**
The optimistic concurrency feature `If-None-Match` does not work when `AllowBulkExecution` is enabled. `304 Not Modified` is never observed (even when we would expect it due to a matching ETag).

**To Reproduce**

```csharp
// Microsoft.Azure.Cosmos v3.37.0

var myAccountEndpoint = "example";
var myAccountKey = "example";

var client = new CosmosClient(myAccountEndpoint, myAccountKey, new CosmosClientOptions() {
    // This bug does not occur if the following is false
    AllowBulkExecution = true
});

var myDatabase = "example";
var myContainerName = "example";

var container = client.GetContainer(myDatabase, myContainerName);

var myDocumentId = "1234";
var myPartitionKey = "abcd";
var myCachedETag = "xxxx";

using var response = await container.ReadItemStreamAsync(
    myDocumentId,
    new PartitionKey(myPartitionKey),
    // This If-None-Match never successfully yields a not modified,
    // even when the correct/latest ETag was supplied!
    new ItemRequestOptions() { IfNoneMatchEtag = myCachedETag },
    CancellationToken.None
);

// response.StatusCode is always HttpStatusCode.OK
// There is no CosmosException thrown where exception.StatusCode == HttpStatusCode.NotModified
```

**Expected behavior**
A `304 Not Modified` should be observed (via a thrown CosmosException) when the document ETag matches the latest version.

**Actual behavior**
The result is always `200 OK`, with the full resource present in the response body.

**Environment summary**
SDK Version: 3.37.0
OS Version: Windows

**Additional context**
I spent a bit of time stepping through `Microsoft.Azure.Cosmos`. I can see that the SDK is correctly writing a value for `ifNoneMatch` in the `ItemBatchOperation.WriteOperation` method, but the resulting `TransactionalBatchOperationResult` is always a `200 OK`.

**Comment by ealsur** [comment] 2023-11-22 19:40
Duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1581

**Comment by nickwb** [comment] 2023-11-22 23:16
Oh, I see. My apologies for not identifying the existing issue.

**Comment by ealsur** [comment] 2023-11-27 15:26
Closing as duplicate. This is a bug on the service.

**Closed by ealsur** 2023-11-27 15:26 UTC
Labels: needs-investigation, customer-reported, Service Bug
