### ISSUE TITLE
RequestCharge not visible in ItemResponse

### ISSUE THREAD

**Issue by icdavid** [Azure/azure-cosmos-dotnet-v3#1414] opened 2020-04-22 00:44 UTC
I'm using the 4.0.0-preview3 version of the API, against Cosmos DB emulator on Windows 10. 

I'm making the following call:

`var obj = await container.UpsertItemAsync<dynamic>(org, new PartitionKey(org.orgId));`

My issue is that the **ItemResponse<dynamic>** object returned by this call does not have an accessible RequestCharge property as documented. Is this by design? If so, is there another way to get the request charge?

Note: if I investigate the returned object in Watch during runtime, RequestCharge appears to be available at **obj.GetRawResponse().Diagnostics.RequestCharge**. However, it's not available at compile time.

**Comment by ealsur** [comment] 2020-04-22 01:23
This is by design. RU charge is a documented header that you can simply get from the Response https://docs.microsoft.com/en-us/rest/api/cosmos-db/common-cosmosdb-rest-response-headers

All diagnostic information is pushed to the diagnostic pipeline present in Azure SDK.

As a side note, are you trying to track RU usage for a particular reason from the code that is not compatible with checking the information on the Monitoring APIs? https://docs.microsoft.com/en-us/azure/cosmos-db/monitor-cosmos-db

**Comment by ealsur** [comment] 2020-04-22 01:24
Closing as by design.

**Closed by ealsur** 2020-04-22 01:24 UTC

**Comment by icdavid** [comment] 2020-04-22 01:49
Well...I am not familiar with the Monitoring APIs...so until I am, I'll just say that I want to collect info about RU consumption at a pretty granular level as I write code against Cosmos DB for the first time. For example, I want to compare things like whether it is more efficient to store list items in a virtual partition within a unitary document or as separate associated documents. I want to understand the trade-offs. Also I am developing using the emulator which is not supported by the Monitoring APIs, correct?

**Comment by ealsur** [comment] 2020-04-22 17:09
Good point!
The story of V4 is that is a version that is aligning with the Azure Core SDK guidelines and is reviewed and iterated with that team, following the other Azure SDKs to provide a consistent model.
The only header that is programmatically required is Session or ETag, because they are either needed for Session consistency operations or optimistic concurrency (so you need specific programmatic support). 
The rest, are headers that are used for telemetry/logging/diagnostics purposes and do not require programmatic support (diagnostics is mainly covered through the Azure Core pipeline and production RU measurement is available through Monitoring APIs), but all are available in the Response's Headers, so you can still get those values regardless of the promoted property. I guess the line is drawn that way on the guidelines.
