### ISSUE TITLE
Ensure DNS changes are detected by client

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#3658] opened 2023-01-17 20:26 UTC
Background: https://azure.status.microsoft/en-us/status/history/ Tracking ID: VN11-JD8

Reference: https://www.meziantou.net/avoid-dns-issues-with-httpclient-in-dotnet.htm

Azure SDK reference: https://github.com/Azure/azure-sdk-for-net/issues/19457

Azure SDK has followed this article and added the default configuration to HttpClient on https://github.com/Azure/azure-sdk-for-net/pull/19524

More code pointers:

* https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L146-L157
* https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/ServicePointHelpers.cs#L61

We should evaluate if we want to follow this approach, the Azure SDK went through these changes so we can assume they are ok, but it's worth investigating.

There is the alternative that none of these APIs are available for NETStandard 2.0

**Comment by ealsur** [comment] 2023-02-16 18:40
Our SDK is a `netstandard2.0` library, so we can only leverage the APIs that are available.

We use `HttpClientHandler` internally when creating the `HttpClient`:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4e923da024956732acfa44a5205104cdd751bee4/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L102-L104


https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4e923da024956732acfa44a5205104cdd751bee4/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L91-L92

In `netstandard2.0`, the `HttpClientHandler` (which inherits from `HttpMessageHandler`) does not include the `PooledConnectionLifetime` property to be set.

When looking at the Azure SDK PR, they are multi-targetting `Azure.Core` and using compilation flags to set this option only when `NETCOREAPP` is the target and it uses the `SocketHttpHandler` that does not exist in `netstandard2.0`:


https://github.com/Azure/azure-sdk-for-net/blob/b983a7055f67d486679e5e66d2fc7d079b73cd93/sdk/core/Azure.Core/src/Pipeline/ServicePointHelpers.cs#L79-L90

```
#if NETCOREAPP
                case SocketsHttpHandler socketsHttpHandler:
                    if (socketsHttpHandler.MaxConnectionsPerServer == RuntimeDefaultConnectionLimit)
                    {
                        socketsHttpHandler.MaxConnectionsPerServer = IncreasedConnectionLimit;
                    }
                    if (socketsHttpHandler.PooledConnectionLifetime == DefaultConnectionLeaseTimeoutTimeSpan)
                    {
                        socketsHttpHandler.PooledConnectionLifetime = IncreasedConnectionLeaseTimeoutTimeSpan;
                    }
                    break;
#endif
```

However, because we expose a hook to `HttpClientFactory` customers can customize the HttpClient themselves, this means that if the customer application is on .NET 6 for example, they can do:

```
public void ConfigureServices(IServiceCollection services)
{
	SocketsHttpHandler socketsHttpHandler = new SocketsHttpHandler();
	socketsHttpHandler.PooledConnectionLifetime = TimeSpan.FromMinutes(10); // Customize this value based on desired DNS refresh timer
	services.AddSingleton<SocketsHttpHandler>(socketsHttpHandler);

	services.AddSingleton<CosmosClient>(serviceProvider =>
	{
		SocketsHttpHandler socketsHttpHandler = serviceProvider.GetRequiredService<SocketsHttpHandler>();
		CosmosClientOptions cosmosClientOptions = new CosmosClientOptions()
		{
			HttpClientFactory = () => new HttpClient(socketsHttpHandler, disposeHandler: false)
		};

		return new CosmosClient("<connection-string>", cosmosClientOptions);
	});
}
```

If they use Dependency Injection, or if they don't:

```
// Assuming this is all Singleton
SocketsHttpHandler socketsHttpHandler = new SocketsHttpHandler();
socketsHttpHandler.PooledConnectionLifetime = TimeSpan.FromMinutes(10); // Customize this value based on desired DNS refresh timer

CosmosClientOptions cosmosClientOptions = new CosmosClientOptions()
{
	HttpClientFactory = () => new HttpClient(socketsHttpHandler, disposeHandler: false)
};

return new CosmosClient("<connection-string>", cosmosClientOptions);
```

Reference: https://devblogs.microsoft.com/cosmosdb/httpclientfactory-cosmos-db-net-sdk/#sharing-httpclients

**Comment by kirankumarkolli** [comment] 2023-02-16 18:46
Agreed on multi-targeting. 

One hypothesis is that custom handler is only used in rare cases => default multi-targeting will benefit majority of CX.

**Comment by ealsur** [comment] 2023-02-16 18:52
If we multi-target, we can definitively do it internally. Yes, my assumption would be that customers rarely customize the HttpClientFactory

**Comment by kirankumarkolli** [comment] 2023-02-16 23:33
Few options (from offline conversation)
- Reflection per platform: Security aspects to be explored
- Account refresh: Isolated client and re-create every time (forcing new connection)
- DNS monitoring and re-create HttpClient OnChange

**Comment by philipthomas-MSFT** [comment] 2023-02-21 16:39
reflection to try to do it we happen to be running on .NET6 - Kevin P.

**Comment by ealsur** [comment] 2023-03-03 19:05
## Potential solutions

1. Multi-target SDK to `net6`
2. Create an independent HttpClient only for GlobalEndpointManager and re-create it each time the account information is fetched.
3. Use Reflection to test if the runtime can create an instance of `SocketsHttpHandler`, if so, then use that to create the base HttpClient with `PooledConnectionLifetime`.

## Solution 1

| Pros | Cons |
|------|------|
|  Strongly tiped APIs when available | **Major time** investment to validate functionality across, not a short term solution     |
|  We can leverage new APIs across other .NET types that can bring performance improvements    |      |

## Solution 2

| Pros | Cons |
|------|------|
|  Disposing/Recreating the HttpClient will force the DNS clearing | Code complexity is elevated, requires un-wiring the single HttpClient we use for the whole SDK and maintain a new one inside GlobalEndpointManager |
|  Existing strongly typed APIs (HttpClient.Dispose) | When we eventually multi-target (Solution 1), it will require un-doing the work because it can be done through the APIs on SocketHttpHandler |
|  Does not require extra validations on how the APIs behave on different frameworks |      |

## Solution 3

| Pros | Cons |
|------|------|
|  Focused code change on the creation of the single HttpClient instance | Using Reflection is not trivial and requires try/catch statements to handle the case where the desired API is not available |
|  Easier migration to multi-targeting than Solution 2 because it will require to just remove Reflection and use the existing APIs | Requires validation on at least .NET Framework 4.8 and .NET 6 to see the behavior (.NET 6 would benefit, .NET 4.8 would not) |

**Comment by NaluTripician** [comment] 2023-03-07 21:41
# Findings on .NET Detection of DNS Changes 

Here are my findings on the current behavior of .NET 6.0 and 4.8 in regard to how DNS changes are detected. For all the following test, first an instance of a `HttpClient` is created. Then the console app enters the following loop: 

```
while (true)
{
    HttpRequestMessage request = new HttpRequestMessage
    {
        Method = HttpMethod.Get,
        RequestUri = new Uri("http://fakeURL.com")
    };

    try
    {
        HttpResponseMessage res = await client.SendAsync(request,
        HttpCompletionOption.ResponseHeadersRead);
        Console.WriteLine(res);
        res.Dispose();
    }
    catch (TaskCanceledException) 
    {
        Console.WriteLine("Task Canceled");
    }
    
    await Task.Delay(TimeSpan.FromMinutes(1));
}
```

While in the loop, changes are made to the `hosts` file on my local machine that will point the fake url to different IP addresses. It is also important to note that all of the `HttpClient` have a `Timeout` value set to 65 seconds to mirror the behavior of the SDK (the default is 100 seconds).

## .NET 6.0 - Default Behavior

In .NET 6.0, changes to the IP address are only detected if a new Http Connection is made. This happens in two circumstances: 
1. When the `Delay` of the console app is longer than the `Timeout` value on the `HttpClient`
2. After the First `SendAsync` call.

For the second scenario, if after the first `SendAsync` call you change the IP address in the `hosts` file, the change will be detected by the client, as it is opening a new connection. However, if you then change it again for the third or subsequent calls, the change will not be detected. Additionally, if you change the IP for the first time after the second or subsequent calls of `SendAsync` the change will not be detected. 

This is the expected behavior based on the customer reported issues.

## .NET 4.8 - Default Behavior

 `dotnet-counters` does not work for this version so the behavior with creating new Http Connection is a guess based off of the .NET 6.0 behavior. 

 Unlike .NET 6.0, if the IP address change is made after the first `SendAsync` call, the change is not detected. 
 However, if the IP address change is made after the second `SendAsync` call, the change is detected.
 If the IP address change is made after the third `SendAsync` call, the change is not detected for the fourth `SendAsync` call but is for the fifth. Changing the IP address again there, the change is not detected. 

 Changing the `Timeout` value back to the default of 100 did not affect this. 

 These are strange results and there might be a need to further investigate why this difference happens. 


## Using Reflection to create an Instance of `SocketsHttpHandler`

To test to see if using reflection is a viable option, I created a separate library that both the .NET 4.8 and 6.0 console apps call to create the `HttpClient`. Here is what that library looks like: 

```
public static (HttpClient, string) CreateHttpClient()
{
    try
    {
        Type socketHandlerType = Type.GetType("System.Net.Http.SocketsHttpHandler, 
            System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");

        object socketHttpHandler = Activator.CreateInstance(socketHandlerType);

        PropertyInfo pooledConnectionLifetimeInfo = socketHandlerType.GetProperty("PooledConnectionLifetime");
        pooledConnectionLifetimeInfo.SetValue(socketHttpHandler, TimeSpan.FromMinutes(10), null);

        return (new HttpClient((HttpMessageHandler)socketHttpHandler, disposeHandler: false), ".NET 6.0");
    }
    catch
    {
        Console.WriteLine("\n\n\nFailed to make SocketHttpHandler ");
    }    
    return (new HttpClient(), ".NET 4.8 or Other");
}
```
### .NET 6.0 Behavior 

The IP address changes are detected, but it happens Http Connections are dropping and a new one is connected. When changing the `PooledConnectionLifetime` field to 10 seconds instead of 10 minutes, the changes are detected every time.

### .NET 4.8 Behavior

Behaves the same as the default .NET 4.8 as expected. 

## Unanswered questions and Conclusions.

The first concern is that is changing the `hosts` file good enough to replicate a scenario where DNS changes actually happen? There is some inconsistent behavior and is changing the `hosts` file the cause? 

Second is why are Http Connections closed? What factors/scenarios cause an HTTP connection to close? When a connection closes, from what I can see, then the changes to the `hosts` file are visible to the client. 

Third is what are should the `TimeSpan` value be if this solution is used in the SDK? See earlier comments in the .NET 6.0 Behavior with Reflection Section.

**Comment by Pilchie** [comment] 2023-03-07 21:56
> For the second scenario, if after the first SendAsync call you change the IP address in the hosts file, the change will be detected by the client, as it is opening a new connection.

Why is it opening a new connection for the second request, but not any subsequent requests?

**Comment by Pilchie** [comment] 2023-03-07 21:57
@karelz - Wondering if you can help us out with some DNS related queries.  Part of Azure Cosmos DB's strategy for moving to different regions involves updating DNS, but we recently observed some cases where our clients didn't pick up the changes, and we're trying to make the SDK work better in these sort of cases.

It's complicated by the fact that we're a .NET Standard 2.0 library, and still have plenty of use on .NET Framework.

**Comment by ealsur** [comment] 2023-03-07 22:01
> > For the second scenario, if after the first SendAsync call you change the IP address in the hosts file, the change will be detected by the client, as it is opening a new connection.
> 
> Why is it opening a new connection for the second request, but not any subsequent requests?

Good question, @NaluTripician can you confirm this? With the default HttpClient, iIf the Timeout is 65 seconds and requests are happening faster, if you change the hosts file, is it picking up the changes or is it not? My understanding was that it was not, but the sentence seems to imply the contrary?

**Comment by NaluTripician** [comment] 2023-03-07 22:40
> > > For the second scenario, if after the first SendAsync call you change the IP address in the hosts file, the change will be detected by the client, as it is opening a new connection.
> > 
> > 
> > Why is it opening a new connection for the second request, but not any subsequent requests?
> 
> Good question, @NaluTripician can you confirm this? With the default HttpClient, iIf the Timeout is 65 seconds and requests are happening faster, if you change the hosts file, is it picking up the changes or is it not? My understanding was that it was not, but the sentence seems to imply the contrary?

I think I might know what’s going on here, there is a 10 second delay I added before the loop in the test to give me time to start the `dot-net counters` which is longer than the Timeout value. I will update the original comment where this is not an issue.

**Comment by NaluTripician** [comment] 2023-03-08 14:37
> 

After some more testing I do not think that this is the issue. I am still seeing the connection drop after the first send, even when setting the `PooledConnectionLifetime` / `Timeout` values to large amounts of time.

**Comment by NaluTripician** [comment] 2023-03-08 18:46
Another possible reason that the HTTP connections were being dropped in the test was that the target IP address used had no keepalive,

**Comment by NaluTripician** [comment] 2023-03-09 21:57
Updated original comment with results from fix to tests.

**Comment by karelz** [comment] 2023-03-21 10:56
@Pilchie sure, we can try. However note that DNS is done by OS on both .NET Framework and .NET Core. We as .NET do not interact with it, we just use it and leave all policy decisions and other fun stuff to OS.
Do you have any specific questions or suggestions?

BTW: We toyed with the idea to implement our own DNS - see https://github.com/dotnet/runtime/issues/19443. It has upsides (TTL available, etc.) and also downsides (no cross-process sharing which OS does). As a result, we didn't see huge need given that it would be only an alternative without clear winner between the 2 implementations.

**Closed** 2023-04-07 21:18 UTC
Labels: Transport
