### ISSUE TITLE
Not using Custom Serializer in linqSerializerOptions

### ISSUE THREAD

**Issue by SigridAndersen** [Azure/azure-cosmos-dotnet-v3#3769] opened 2023-03-20 12:35 UTC
**Describe the bug**
Custom serializer options are not used when using GetItemLinqQueryable.

**To Reproduce**
```
var customSerializer = new NewtonsoftJsonCosmosSerializer(new JsonSerializerSettings { DateFormatString = "yyyy-MM-ddTHH:mm:ss.fffZ" });
var cosmosClient = new CosmosClient("myConnectionString"), new CosmosClientOptions { ConnectionMode = ConnectionMode.Gateway, Serializer = customSerializer });
myContainer = cosmosClient.GetContainer("database", "container");

var myDateTime = DateTime.UtcNow
await myContainer.CreateItemAsync(new MyClass { Id = Guid.NewGuid(),  MyDateTime = myDateTime })

var iterator = myContainer.GetItemLinqQueryable<MyClass>()
    .Where(c => c.MyDateTime == myDateTime)
    .ToFeedIterator();

var result = new List<MyClass>();
while (iterator.HasMoreResults)
{
    result.AddRange(await iterator.ReadNextAsync());
}

var item = result.FirstOrDefault();

Assert.NotNull(item)
```

**Expected behavior**
Expected to find the item that was just created.

**Actual behavior**
Item is not found. The generated query is
`SELECT VALUE root FROM root WHERE (root["MyDateTime"] = "2023-03-20T12:28:12.1353978Z"`
with the custom datetime serialization, the query should actually be
`SELECT VALUE root FROM root WHERE (root["MyDateTime"] = "2023-03-20T12:28:12.135Z"`

**Environment summary**
SDK Version: 3.32.2 (3.32.1 works as expected)

**Additional context**
The problem seems to be because `CustomCosmosSerializer = this.ClientContext.ClientOptions.Serializer` is removed from the linqSerializerOptions in this commit: https://github.com/Azure/azure-cosmos-dotnet-v3/commit/682b0011dd8224fbbd8f66691abf28cb53929e28

**Comment by ealsur** [comment] 2023-03-20 16:04
Duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3697.

The serializer was removed because the PR that added it caused other regressions, please see the linked issue. The team is working on a different fix for this.

**Closed by ealsur** 2023-03-20 16:04 UTC
Labels: needs-investigation
