### ISSUE TITLE
Query: Crosspartitions ORDER BY Queries consume large RUs while using pagination

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#2804] opened 2021-10-18 20:02 UTC
In V3 SDK:

OrderByQuery uses [K-way Sort Alogirithm](https://en.wikipedia.org/wiki/K-way_merge_algorithm) in order to return ordered results for a cross partition Query. 

Lets suppose, we have data (9 records) in 5 partitions and sorting is ascending order with MaxItemCount per page is 1:
1. When we are reusing the iterator, then it queries each partitions (5 network calls) for sorted data and take the top result from them and then return the smallest value from the list of records. and second page onwards it skip all those partitions which doesn't have any data.
Then, requery only the last partition from where we got the smallest value. (so 1 call each page).

So it is making 1 * 5 + 8 * 1 = 13 Network calls.

2. When we are NOT reusing the iterator, then it queries each partitions (5 network calls) for sorted data and take the top result from them and then return the smallest value from the list of records. and create a continuation token with the same information.
Then, requery all 5 partitions everytime to compare and get the smallest value out of it. (so 5call each page).

So it is making 1 * 5 + 8 * 5 = 45 Network calls.

PR which has related testcase and console logs (it doesn't have the fix) : https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2782
Bug reported by customer : https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2756

Verified same scenario in V2,  Same number of RUs are getting consumed in both the cases.

**Comment by neildsh** [comment] 2023-02-13 18:28
Duplicate of #2756

**Closed by neildsh** 2023-02-13 18:28 UTC
Labels: bug, needs-investigation, QUERY
