### ISSUE TITLE
Can't execute async LINQ queries

### ISSUE THREAD

**Issue by adrianknight89** [Azure/azure-cosmos-dotnet-v3#665] opened 2019-08-10 16:09 UTC
I get an `IOrderedQueryable<T>` from `GetItemLinqQueryable<T>()` and follow up with a `Where()` and `OrderBy` clause and finally convert the whole thing to a `FeedIterator<T>`. Since the default value for `allowSynchronousQueryExecution` is false, everything should be async. However, I get the following exception:

> System.NotSupportedException: To execute LINQ query please set allowSynchronousQueryExecution true or use GetItemsQueryIterator to execute asynchronously

Can you please tell me what I'm doing wrong? Is async LINQ not supported right now? If so, what's the purpose of `allowSynchronousQueryExecution`? I'm using SDK 3.1.0.

**Comment by j82w** [comment] 2019-08-12 11:32
Hi @adrianknight89,

Can you provide a code example with a repo?

**Comment by j82w** [comment] 2019-08-12 14:53
I'm closing this as a duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/589

**Closed** 2019-08-12 14:53 UTC
Labels: LINQ, bug, duplicate, needs-investigation
