### ISSUE TITLE
LINQ Skip Take translated to wrong SQL statement

### ISSUE THREAD

**Issue by canergur** [Azure/azure-cosmos-dotnet-v3#3626] opened 2023-01-03 11:10 UTC
**Description**
Skip Take methods are translated in a wrong way when sending SQL query to the Cosmos DB when using the cosmos SDK.

**Steps to Reproduce**
```
var queryable = container.GetItemLinqQueryable<SomeClass>(true, null, options);
queryable.Skip(100).Take(10);
```

**Expected**
It's expected to be translated to 

`SELECT * FROM root OFFSET 100 LIMIT 10`

**Actual**
But actually it's translated to 
`SELECT * FROM root OFFSET 0 LIMIT 110` while sending http request to cosmos DB to get results. 
So it causes to fetch all the results from database even if we need only 10. Eventually, method returns correct amount of results though. I assume Skip and Limit is happening on client side. 

**Environment summary**
SDK Version: 3.31.2
OS: Windows

**Comment by canergur** [comment] 2023-01-11 13:27
Hello, @SebastianVeile. It seems to be related. 
Yes, the SQL statement has been changed somewhere in SDK before sending it in HTTP request, although the statement is correct if you check it using `CosmosLinqExtensions.ToQueryDefinition(queryable)`

**Comment by adityasa** [comment] 2023-07-11 05:25
@canergur this is by design. The query gets rewritten, especially to accommodate cross partition collection scenario where a partition may or may not yield desired number of results (10 in this case) and leverage request parallelization at the same time. OFFSET...LIMIT calculation is done by the sdk on client side on the results returned by the service.

We have a feature in the works that will improve this in future for single partition collections, where query will not need such a rewrite.
The feature (EnableOptimisticDirectExecute) is available in preview form, on by default and can be used for testing (no production dependency).
https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.35.1-preview
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#added
There are certain tradeoffs associated with using this feature which will be part of upcoming public documentation for this feature. @akotalwar as fyi, who can provide the link once that is available.

**Closed** 2023-07-11 05:26 UTC
Labels: QUERY, LINQ
