### ISSUE TITLE
Unable to load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll' the dll's are present in both bin and runtimes folder

### ISSUE THREAD

**Issue by indira-raghavan** [Azure/azure-cosmos-dotnet-v3#1811] opened 2020-08-27 18:27 UTC
Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 00000000-0000-0000-0000-000000000000; Reason: (Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll' or one of its dependencies: The specified procedure could not be found. (0x8007007F));

I have both Microsoft.Azure.Cosmos.ServiceInterop.dll and Cosmos.CRTCompat.dll in both bin/debug/netcoreapp3.1
and bin/debug/netcoreapp3.1/runtimes/win-x64/native

**Comment by ealsur** [comment] 2020-08-28 02:18
Is this happening locally in your machine or deployed somewhere? Did you recently upgrade the SDK version? Did you do a clean of the folders to remove any old binaries?

Can you repro this on a new project?

**Comment by indira-raghavan** [comment] 2020-08-28 02:26
I have clean cloned the project. The same project exists in my colleagues computer. No issues. The code works in production. Its my local issue. I have windows 7. Code is deployed in azure kubermetes cluster.

I have the cosmos.crtcompat.dll and serviceinterop.dll in both .netcoreapp3.1 folder under debug and under runtimes/win64/native folders.

I even tried adding this path into system path variable.

C:\users\<username>\.nuget\packages\Microsoft.azure.cosmos folder has all the dlls under runtime folder.

I have also checked, windows\system32 and inetsrv folders. They contain this dll too.

I tried adding runtime target copy to .csproj file. To copy the serviceinterop dll.

I am running out of options to try and getting frustrated. Any help in resolving this issue is deeply appreciated.

Thanks,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ealsur** [comment] 2020-08-28 03:15
Can you repro this on a clean new project? Basically create a new project, with the PackageReference and try to run a simple query outside of your current project? Trying to rule out some setting in the current project.

Basically this is a Windows error unabling to load the DLL, it might be because on runtime, the paths are not the ones where the DLLs are located, normally this would be the bin folder but there might be some environment setting changing it? Could it be permissions on the files for the identity running the app?

The fact that it works on another environment and in production seems to point to some environment configuration affecting this.

**Comment by indira-raghavan** [comment] 2020-08-28 15:14
Hi Matias,

  I added the same library to new project. Getting the same error.

public static List<object> GetData(String container, QueryDefinition query, StoreWaitingListSettings settings)
        {
            FeedIterator<object> queryData = getCosmosContainer(settings, container).GetItemQueryIterator<object>(query);

            List<object> results = new List<object>();
            while (queryData.HasMoreResults)
            {
                var response = queryData.ReadNextAsync().GetAwaiter().GetResult();
                results.AddRange(response.ToList());
            }
            return results;
        }

Microsoft.Azure.Cosmos.CosmosException: 'Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 00000000-0000-0000-0000-000000000000; Reason: (Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll' or one of its dependencies: The specified procedure could not be found. (0x8007007F));'

Getting the container is not the problem. I can establish connection and get the container. It fails on executing the query.



Indira Raghavan
I teach, therefore I learn.
Sr. Software Developer
Customer Application Development
Office: 905-737-1147 ext. 2907
Email: indira.raghavan@staples.ca<mailto:indira.raghavan@staples.ca>

**Comment by indira-raghavan** [comment] 2020-08-28 15:16
Also, I have full permissions and run this project as a administrator. Still have the same issue.

Indira Raghavan
I teach, therefore I learn.
Sr. Software Developer
Customer Application Development
Office: 905-737-1147 ext. 2907
Email: indira.raghavan@staples.ca<mailto:indira.raghavan@staples.ca>

**Comment by ealsur** [comment] 2020-08-28 15:24
The title of the incident says `Microsoft.Azure.Documents.ServiceInterop.dll`, which is the file that is missing? `Microsoft.Azure.Documents.ServiceInterop.dll` or `Microsoft.Azure.Cosmos.ServiceInterop.dll`? This is kind of important, are you using both V2 and V3 in the same project?

**Comment by indira-raghavan** [comment] 2020-08-28 15:27
That was my mistake. Microsoft.Azure.Cosmos.ServiceInterop.dll this is the missing dll.

Indira Raghavan
I teach, therefore I learn.
Sr. Software Developer
Customer Application Development
Office: 905-737-1147 ext. 2907
Email: indira.raghavan@staples.ca<mailto:indira.raghavan@staples.ca>

**Comment by ealsur** [comment] 2020-08-28 15:30
Got it, but does your project have the V2 SDK (Microsoft.Azure.DocumentDB) and the V3 SDK (Microsoft.Azure.Cosmos)?

**Comment by indira-raghavan** [comment] 2020-08-28 15:37
Nope. Just Microsoft.Azure.Cosmos
[cid:image001.png@01D67D2F.89202B10]

Indira Raghavan
I teach, therefore I learn.
Sr. Software Developer
Customer Application Development
Office: 905-737-1147 ext. 2907
Email: indira.raghavan@staples.ca<mailto:indira.raghavan@staples.ca>

**Comment by indira-raghavan** [comment] 2020-08-28 15:56
Hi,

  I used depends.exe to figure out what other dependencies are needed and not present. Copied those dll’s into system32 as well. Still having same issue.

Indira Raghavan
I teach, therefore I learn.
Sr. Software Developer
Customer Application Development
Office: 905-737-1147 ext. 2907
Email: indira.raghavan@staples.ca<mailto:indira.raghavan@staples.ca>

**Comment by ealsur** [comment] 2020-09-01 19:16
Which are the dependencies? ServiceInterop depends on CRTCompat, but it has no other dependencies (and CRTCompat doesn't either).

This might be an issue with Windows 7, the SDK is finding the DLL in the folder but trying to use it yields this error. I suspect the problem is that part of the native code might not be compatible with the OS.

Have you tried on another more recent OS? (Windows 8/10)

**Comment by ealsur** [comment] 2020-09-09 16:33
Closing as no updates in the past 12 days, please reopen in case the issue is still happening and repros on other environments (if possible provide a repro we can also use).

**Closed by ealsur** 2020-09-09 16:33 UTC

**Comment by indira-raghavan** [comment] 2020-09-09 16:34
Hi Matias,

  The issue was with windows 7. I tried the same project on windows 10 laptop. And 8t works. Thank you for your help.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
