### ISSUE TITLE
[QUERY] Azure Cosmos Db Distinct values across all pages

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#3634] opened 2023-01-06 20:51 UTC
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#33341](https://github.com/Azure/azure-sdk-for-net/issues/33341).

### Library name and version

Microsoft.Azure.Cosmos 3.30.0

### Query/Question

Is there a way to get distinct values for a field/subdocument in a partition across all pages? I have been using DISTINCT keyword in our queries but since the documents volume is high in our Cosmos Db Container, we get same values more than once. Any help/pointers would be very helpful.

**Comment by ealsur** [comment] 2023-01-09 18:56
@ssghoda Could you provide examples or some form of repro that can help understand the scenario?

**Comment by ssghoda** [comment] 2023-01-09 19:25
@ealsur So think of a Cosmos Db Container of all US Hotels with partition key of State. Each document has a field for City. Now we want to get distinct cities across a partition. Now if the document volume is huge then even after doing a DISTINCT, you would get same city more than once.

Currently, I am getting all distinct cities from query and then again doing DISTINCT using LINQ in my code so that no same city appears more than once. But I was wondering if this whole thing can be done in Cosmos Db how we do it in T-SQL.

**Comment by ealsur** [comment] 2023-01-09 19:39
> Now if the document volume is huge then even after doing a DISTINCT, you would get same city more than once.

Did you experience this? Having a DISTINCT query return duplicate results? Or is this a hypothetical scenario? If you did experience this, please share the code snippets or some example of what is the query you are using.

If it's hypothetical, maybe @jcocchi / @neildsh could chip in to help answer the conceptual question.

**Comment by ssghoda** [comment] 2023-01-09 22:05
I hope I am not the first person to come across this. I have seen this for a long time. But like I said, I have been getting results from Cosmos Db and then doing another Distinct using LINQ in-memory. I just thought to ask this time if there was a way to do this.

![image](https://user-images.githubusercontent.com/65625217/211417378-9c604364-e9e7-45ce-a228-aab7e661117e.png)

![image](https://user-images.githubusercontent.com/65625217/211417494-a0e83100-5d17-4e2a-b4bb-1e0074100466.png)

**Comment by ealsur** [comment] 2023-01-09 22:13
@ssghoda Thanks for this valuable details. When you run the query on the .NET SDK, do you get the same behavior?

**Comment by ealsur** [comment] 2023-01-10 22:36
> Maybe then it is the issue on Azure Portal / Azure Storage Explorer.

Definitively looks like it.

> So if someone has to create an Azure Search Index using this query, which SDK would it use to generate documents in Azure Search?

Are you asking about the Azure Search Indexer? (https://learn.microsoft.com/en-us/azure/search/search-howto-index-cosmosdb)
If yes, they use the .NET SDK as far as I know.

**Comment by ssghoda** [comment] 2023-01-11 23:13
> Definitively looks like it.

Is there any way to inform team for Azure Portal / Azure Storage Explorer to make changes in their side to reflect .NET SDK version so that even in there, we get proper results?

> Are you asking about the Azure Search Indexer? (https://learn.microsoft.com/en-us/azure/search/search-howto-index-cosmosdb)
> If yes, they use the .NET SDK as far as I know.

Yes, awesome. Thanks a lot for your help in confirmation.

**Comment by ealsur** [comment] 2023-01-11 23:14
> Is there any way to inform team for Azure Portal / Azure Storage Explorer to make changes in their side to reflect .NET SDK version so that even in there, we get proper results?

NodeJS SDK is maintained on https://github.com/Azure/azure-sdk-for-js/issues, I'd recommend reporting it there.

I will close this issue now as the problem is not present in this SDK.

**Closed by ealsur** 2023-01-11 23:14 UTC
Labels: QUERY, needs-more-information
