### ISSUE TITLE
Losing records on bulk inserts 

### ISSUE THREAD

**Issue by jtrinidadS** [Azure/azure-cosmos-dotnet-v3#2125] opened 2021-01-15 15:39 UTC
**Describe the bug**

We are currently developing a .NetCore 3.1 + Azure AppService + CosmosDB (serverless mode) solution. One of the features of this app is to insert a large amount of data in a short period of time. To reach this we are using Bulk Insert available in Azure.Cosmos 3.15.1 package.
We tested this approach in three different scenarios with these results:

1.**Localhost in developer PC:** 25.000 records in 2’ 20”, no error response and all records were inserted properly.
2.**QAS** in Azure AppService with MPN subscription: same 25.000 records but in less than a minute. But with lots of Http 429 responses and some records lost (not inserted). This could be solved temporary with a workaround: elevating “MaxRetryAttemptsOnRateLimitedRequests” from 9 (default) to 30. But this is not a permanent solution, because if the records quantity increases the errors will come back.
3.**PRD** in Azure AppService with Enterprise subscription: similar situation to QAS, also losing records (about 1800 records in both scenarios). Applying the workaround we reduced loses to 400 records (MaxRetry = 20) and then to 0 records (MaxRetry = 30).

With these tests we realized that “MaxRetryAttemptsOnRateLimitedRequests” should be set in proportion to the amount of records. The larger the data set, the higher the retries. But only for this temporary workaround. We cannot consider this a permanent solution.
We also noticed that on QAS and PRD, Cosmos returns a very high amount of Http 429 responses. Indicating a possible saturation of the Cosmos API or Resource.

**To Reproduce**

``` C#
   CosmosClientOptions options = new CosmosClientOptions { AllowBulkExecution = true };
  _client = new CosmosClient(_config.GetValue<string>("CosmoDb:Host"), _config.GetValue<string>("CosmoDb:Password"), options);

public async Task AddDateCosmosDBAsync(string jsonText, string dataDomainName)
        { //se añade información a los contenedores, se crea un contenedor si es que no existe con el nombre del dominio de datos que corresponda.
            Stopwatch stopwatch = Stopwatch.StartNew();
            _logger.LogInformation("Comenzo la inserción en cosmos db.");
            Container container = await _database.CreateContainerIfNotExistsAsync(new ContainerProperties { Id = dataDomainName, PartitionKeyPath = "/id" }); 

            JsonDocument jsonDocument = JsonDocument.Parse(jsonText); //el archivo de texto json creado en la validación del excel se parsea a JsonDocument.
            JsonElement element = jsonDocument.RootElement; //se extrae el root element del json (el contenido)

            var elements = element.EnumerateArray(); //se transforma en una array en el que se va iterando.
            int count = 0;
            List<Task> tasks = new List<Task>();

            while (elements.MoveNext())
            {
                var doc = elements.Current; //cada doc, es el elemento json que esta iterando en este momento. (un objeto)
                if (count != 0) //el primer elemento no lo guardamos, porque es el nombre de las columnas.
                {
                    Console.WriteLine(doc);
                    var id = doc.GetProperty("id").ToString(); //se extrae el id para el partitionKey (es necesario para la indexación)
                    var raw = doc.GetRawText(); //se convierte el objeto json en raw text para pasarlo a stream.
                    byte[] bytes = Encoding.UTF8.GetBytes(raw);
                    using (var stream = new MemoryStream(bytes))
                    {
                        tasks.Add(container.CreateItemStreamAsync(stream, new PartitionKey(id))
                               .ContinueWith((Task<ResponseMessage> task) =>
                               {
                                   using (ResponseMessage response = task.Result)
                                   {
                                       if (!response.IsSuccessStatusCode)
                                       {
                                           _logger.LogInformation($"Received {response.StatusCode} ({response.ErrorMessage}).");
                                       }

                                   }
                               })); //se inserta el dato en formato Memory Stream, acompañado del id generado anteriormente.
                    }
                }
                count++;
            }

            await Task.WhenAll(tasks); //se lanza la inserción masiva.

            stopwatch.Stop();
            _logger.LogInformation($"Finished in writing {count} items in {stopwatch.Elapsed}.");
        }
```

**Expected behavior**

Cosmos should be able to handle a 25K (or more) records Bulk insertion and eventually Http 429 responses with no records lost.

**Actual behavior**

CosmosDB returns lots of Http429 and loses records in Bulk Insertion. And the amount of errors is proportional to the amount of records to insert.

**Environment summary**

**Local environment:** 
SDK Version: 3.15.1 
OS Version: Windows 10.0.18363 Build 18363
**QAS:** 
App Service Plan: S1.
OS: Windows
**PRD:** 
App Service Plan: P1v2. 
OS: Windows

**Additional context**

Some useful screenshots of Azure Monitor and App Service Logs for every scenario, to compare duration time and amount of retries. 

**DEV :** local developer PC, all records inserted successfully, no Http 429 and no records lost. Without applying the “MaxRetry” workaround.
![image](https://user-images.githubusercontent.com/66782466/104746414-0477bc00-572e-11eb-8f0a-aeedd6627235.png)

**QAS:** Applying the “MaxRetry” workaround to 30 we could achive inserting without losing records, but getting lots of Http 429 responses.
![image](https://user-images.githubusercontent.com/66782466/104746473-19ece600-572e-11eb-9b78-7787105304ef.png)
![image](https://user-images.githubusercontent.com/66782466/104746489-1d806d00-572e-11eb-8099-23095f213d91.png)

**PRD:**  Similar to QAS, applying the “MaxRetry” workaround to 30.
![image](https://user-images.githubusercontent.com/66782466/104746540-2f621000-572e-11eb-9047-c3656652288a.png)
![image](https://user-images.githubusercontent.com/66782466/104746548-325d0080-572e-11eb-9c83-584cd04344df.png)

**Comment by ealsur** [comment] 2021-01-15 17:42
429 or throttling is independent of Bulk. Bulk is a optimized mode that will reduce the client-side bottleneck of having to do individual network requests to save the volume of data you want to save. It will **not reduce the number of 429s**. What it does (ref https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/) is pack the data into less network requests, which makes your application send more data, faster.

Conceptually, your container has X provisioned RU, each operation consumes some RU, and your provisioned RU let's you do Y operations per second. If you are trying to save a volume of data (with or without Bulk) that exceeds the capacity of your provisioned throughput, you will get 429s, that is unavoidable.

If you know the volume of data will surpass your processing capacity, you should either reduce the volume of data you send at a given time or increase the provisioned throughput to accommodate your needs.

The records that are "lost" are basically because you are exhausting your provisioned RUs and those are returned as errors with a 429 status code.

The reason for your local dev environment to complete without 429s is obvious, your machine is further away from the database, so the rate at which you are sending your data is slower, so it is giving more breathing room for the provisioned RU/s (per second). When running in App Service, which is closer, your application can push data faster, because the network requests complete faster. Since you are pushing data faster, your provisioned RU/s are exhausted.

**Comment by Mortana89** [comment] 2021-01-15 21:24
You should take a look at Polly.
 (https://github.com/App-vNext/Polly)
With Polly you should be able to gracefully catch 429s and indefinitely keep retrying, potentially with an exponential backoff policy.

**Comment by ealsur** [comment] 2021-01-15 21:44
While Polly is a great library, this can be achieved also by increasing the SDK retries on 429s through: 

* CosmosClientOptions.MaxRetryAttemptsOnRateLimitedRequests

You can increase it to a higher value, it will make the whole bulk operation take much longer and eventually complete.

But the root cause is that the volume of data you are trying to send is higher than your capacity to process operations through the provisioned throughput.

**Comment by jtrinidadS** [comment] 2021-01-19 12:21
@ealsur 
Apparently the best solution was to pack the requests with ten inserts each, just like the link example.

However, it is not possible to read or modify the provisioned performance since I am working with serverless, when trying to read or modify the API it returns an error, as indicated by the documentation in this regard. Is there any other way to know my provisioned performance when using serverless?

@Mortana89 
As I mentioned before, I do not consider a good practice to increase the number of retries to a fixed number, since it should increase respectively the amount of data that is tried to be inserted in the application and its hard to control.

**Comment by ealsur** [comment] 2021-01-19 18:31
@jtrinidadS I'm not sure how Serverless works with throttles, @ThomasWeiss do we have any information on that?

**Comment by ThomasWeiss** [comment] 2021-01-19 18:33
Serverless containers currently deliver up to 5,000 RU/s of throughput. We plan to increase this limit and provide a way to read the current deliverable throughput.

**Comment by ealsur** [comment] 2021-01-22 16:16
Closing as the reason was identified as requests being throttled and exceeding the retry iterations. Workarounds were provided in the thread (increasing the retry times for example).

**Closed by ealsur** 2021-01-22 16:16 UTC
Labels: Bulk, needs-investigation
