### ISSUE TITLE
Allow Azure region 'short names' when setting ApplicationRegion and ApplicationPreferredRegions

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-cosmos-dotnet-v3#2259] opened 2021-02-26 00:27 UTC
When setting either of these properties, you have to provide a string name of the Azure region(s). But they only accept the 'full' names. So it will accept 'West US' but not 'westus'. We set these values via config setting set by ARM template in a `copy` loop for the different regions that our app is deployed in, and the ARM template allows either the 'short' or 'full' region name. Also, the Azure Management SDK that contains the `Region` class supports both types of values.

![image](https://user-images.githubusercontent.com/1545776/109237392-490f6200-7786-11eb-8be1-7568da35c94e.png)

**Comment by ealsur** [comment] 2021-04-12 23:28
Closing as duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2330

**Closed by ealsur** 2021-04-12 23:28 UTC
Labels: feature-request
