### ISSUE TITLE
FeedIterator Diagnostics: Provide ability to determine LeaseToken along with batches

### ISSUE THREAD

**Issue by bartelink** [Azure/azure-cosmos-dotnet-v3#1122] opened 2019-12-28 02:42 UTC
**Is your feature request related to a problem? Please describe.**
Regardless of the configuration being applied, being able to see which ranges are being serviced (in terms of physical rangeids) is critical for troubleshooting feed performance.

While simply logging the value (`received 100 items from Range 4`) is one use it might be applied to, in some cases, it can be useful for internal routing prioritization too - i.e. "ok we'll stuff something into the log deep down" does not address the need in full.

**Describe the solution you'd like**
The callback that delivers a set of feed items should in some way convey the range id, as the V2 one did. 

**Describe alternatives you've considered**
I'm not aware of any way to determine where a batch of items came from

**Additional context**
This is to some degree a restatement of items covered in #616, prompted by #1117. While I like the new APIs, not having this is a deal breaker for moving applications onto any SDK newer than V2, which is a major concern for me.

**Comment by ealsur** [comment] 2020-01-02 16:39
Is the information exposed as Diagnostics not enough to do that analysis?

* https://docs.microsoft.com/en-us/azure/cosmos-db/monitor-cosmos-db#azure-cosmos-db-log-analytics-queries-in-azure-monitor
* https://docs.microsoft.com/en-us/azure/cosmos-db/monitor-cosmos-db-reference

It seems like the doc does not mention it, but there used to be a "partitionId" field in the Diagnostics Logs.

**Comment by bartelink** [comment] 2020-01-02 17:06
While it may be possible to infer it from that (obviously rich) source, the point is that I want to be able to correlate from _my_ logs, that I have 2 instances of my CFP, and the rate of progress per range across those instances. Knowing that there are two things out there querying is a good start, but does not let me troubleshoot a specific CFP node's behavior in terms of the actual changes being observed (or not, as can frequently be the case e.g. if you get a hot partition)

**Comment by bartelink** [comment] 2020-01-02 17:10
Also, for avoidance of doubt, I/we have stacks of code that emits this context into logs. The fact that this context is being withheld in the >=3 SDK is a significant blocker to adoption of newer SDKs for multiple teams. I can get that one might wish to de-emphasize such ways of troubleshooting, but I fail to see what closing the bottle accomplishes here - perhaps you can explain a little about why you feel its harmful to expose this?

**Comment by ealsur** [comment] 2020-01-02 17:29
The problem is that the concept of the Partition is tied to the current implementation, it's not a piece of information that comes from the service response. Assuming monitoring information from an implementation detail breaks if the implementation changes.

The current implementation is locking 1 lease to 1 Partition (the LeaseToken is the number of PKRange/Partition), so if you see LeaseToken 0 and 1 assigned to one instance, you assume those 2 Partitions are going to be processed by that instance, and you would be right, now. But the end goal is for the leases to not be locked to a Partition, that a Partition can have multiple Leases and thus increase the scaling support and also enable new scaling scenarios, like being able to have multiple CFP Hosts on single Partition containers.

Let's say now that each Partition can be split across 10 Leases (each lease represents now a range of Partition Key Values), if you have 6 Partitions, you have 60 leases. Each lease will have a LeaseToken that represents the range of PK values, not the Partition, because the Partition is not needed anymore. Since the Partition is not something that comes as a response header, even if the SDK exposed the Lease instance, or LeaseToken, that wouldn't let you understand which Partition the request hit.

In that scenario, obtaining the information from the Diagnostics is more valuable to identify Partition consumption, as the leases won't reflect a particular Partition anymore, you won't be able to determine the Partition from the lease, even if it's exposed to the delegates. So Diagnostics is the one implementation-agnostic source of information. In the Diagnostics you can use the UserAgent (which in the V3 SDK is mapped to the ApplicationName in the CosmosClientOptions) if you want to dissect and understand which instance is querying which Partitions.

**Comment by bartelink** [comment] 2020-01-02 17:43
Aside from the fact that this sounds much scarier to troubleshoot than the existing mechanism, my main concern here is that any such scheme with multiple readers per partition will exacerbate write amplification effects (leading to more troubleshooting needs...). _Or are you saying there's be some mechanism whereby there's a relatively low cost server-side filtering applied and I'm not managing a system where multiple readers are triggering network and server traffic?_

For avoidance of doubt, I'm not looking for lease or lease token information to be exposed via the API.

**Comment by ealsur** [comment] 2020-01-02 18:07
Currently the only way to consume the Change Feed is by the PKRange / Partition (hence the 1 lease 1 Partition approach) but this limits the degree of parallelism to a factor that users cannot control directly, which has been asked many times.

We are working on server-side support to enable a higher granularity filter, which would enable this higher granularity in the leases, and basically be able to read changes from ranges of PK values, regardless of Partition distribution.

The problem in any case is that the Partition/PKRangeId, the piece of information you want to log (at least from what I understood is the ask and the need to troubleshoot hot partitions), is not something that is currently exposed in the REST response, so even if the SDK wanted to expose all the information (pass that down), it just wouldn't be there. 

What I don't understand from your comment is your mention of write amplifications. As the CFP is a read-only mechanism, could you elaborate on what do you mean by that and how a higher degree of read parallelism would affect writes?

**Comment by bartelink** [comment] 2020-01-02 18:50
>What I don't understand from your comment is your mention of write amplifications. As the CFP is a read-only mechanism, could you elaborate on what do you mean by that and how a higher degree of read parallelism would affect writes?

If one has 5 Reactors tracking changes using your proposed enhancements, then every write starts triggering 5 reads. This is particularly relevant where one is triggering significant numbers of updates, which normally get 'squashed' per call from a single consumer.

Such a pattern is a common thing to do with Kafka, but of course its design incorporates strong support for scaling out reads.

In the general case, for workloads I'm familiar with, a common pattern is actually to feed from a CFP onto Kafka and let the N readers hang off that; given the write capacity of a Kafka cluster (and the fact you won't encounter rate limiting), it's pretty trivial to manage such a replication chain -- especially if you have good diagnostics as to how far things are behind (and you can drill into partitions that are not yielding reads to the CFP reader) ;) There's also lots of commercial and open-source tooling for such diagnostics.

While I understand the desire people have for such features (pejoratively: pretending Cosmos can and should be able to do all the things Kafka can do), it's critical for me that it doesn't come at the cost of making basic workflows (replicating CFP to a straightforward feed without filtering or major enrichment) harder to troubleshoot than they need to be. Just because someone asked for scissors, doesnt justify blindfolding people with far simpler schemes.

>The problem in any case is that the Partition/PKRangeId, the piece of information you want to log (at least from what I understood is the ask and the need to troubleshoot hot partitions), is not something that is currently exposed in the REST response, so even if the SDK wanted to expose all the information (pass that down), it just wouldn't be there.

The piece of information I want to log is the RangeId - the value that's supplied to the lease assignment notification. I guess if that notification is also not being implemented in newer SDKs, the value goes down.

All that remains for me to do is to restate: with the V2 CFP lib, it was possible to cheaply implement a logging scheme which allows me to store sufficient info to allow me to determine why a pile of notifications were delayed between 1:30am and 2:00am 2 weeks ago - I can see the Range Assignments and Read batches (with Range tagging) and can determine if any Ranges did not receive responses (and I can correlate that with the Change Feed Estimation results logged separately). While you're supplying me lots of powerful new abstractions, I'm keen to understand how you propose that I implement something that achieves that same traceability on the V3 stack before we start using them - a new abstraction is worthless without a troubleshooting story when I'm the one with the pager.

**Comment by ealsur** [comment] 2020-01-02 19:20
> The piece of information I want to log is the RangeId - the value that's supplied to the lease assignment notification. I guess if that notification is also not being implemented in newer SDKs, the value goes down.

This is not fully correct. The RangeId is supplied on V2 CFP because the Lease contains a LeaseToken that matches the RangeId, because the lease is basically, 1 per RangeId, so to separate one Lease from the other, we have the RangeId, but only because the degree of parallelism is the RangeId/Partition, again, this is an implementation detail.

If a new implementation, with a different degree of parallelism comes into the picture, then the value that will be logged is that, not the RangeId. For example, let's just say for the sake of argument that we have a container that has 2 Partitions, 0, and 1, and you have 2 CFP instances. Currently, you see logs that say:

`[CFP 0] assigned range 0`
`[CFP 1] assigned range 1`

And 0 and 1 are really, Partitions, so in V2, you use this value to diagnose requests across partitions.

But in a higher parallelism scenario, with still 2 Partitions, we could go further and say that each Partition is now subdivided into PK value ranges. So Partition 0 is now PKValueRanges A, B, and C, and Partition 1 is now PKValueRanges D, E, and F. In that scenario, you will see logs like:

`[CFP 0] assigned range A`
`[CFP 1] assigned range B`
`[CFP 0] assigned range C`
`[CFP 1] assigned range D`
`[CFP 0] assigned range E`
`[CFP 1] assigned range F`

Now, the Lease identifier is no longer the Partition/RangeId, so even if it's exposed, you will see A, or C, not RangeId 0 or 1, so **if the goal is to track RU usage/Hot partitions**, the Lease information won't be useful, and that's when you need to go to Diagnostics. If the ask is explicitly that you want the RangeId, then it is not possible with a lease mechanism that goes further than the RangeId.

Now, **if the goal is to track per Lease flows / changes**, then this **can be exposed**, because you'd be getting the LeaseToken (whatever that represents, it doesn't matter) and it will be in sync with the "assigned range" logs.

**Comment by bartelink** [comment] 2020-01-02 19:41
Thanks for echoing back - I agree there can be confusion in the more complex cases (you explained it well from the off)

>Now, if the goal is to track per Lease flows / changes, then this can be exposed, because you'd be getting the LeaseToken (whatever that represents, it doesn't matter) and it will be in sync with the "assigned range" logs.

Yes, this is the goal - being able to track assignments and splits. Also, given me and m any others will be going 1:1 parallelism, having a good story for that basic logging (this batch came from `0` is the ask.

**Comment by ealsur** [comment] 2020-01-02 19:44
Awesome! Glad to be on the same page 😄 

Would it be ok to change the title to something like "Supply LeaseToken..." otherwise RangeId would lead to the ask being wrongly interpreted as needing the partition information (that was my initial interpretation).

**Comment by ealsur** [comment] 2020-01-03 18:15
I'll see if this can either go on V3 or vNext due to the breaking change nature on the contract

**Comment by bartelink** [comment] 2020-01-03 18:25
Thanks - from a selfish point of view, V3 isnt any more useful than V4 in terms of whether it'll fit in our environments

I should point out that https://github.com/Azure/azure-cosmos-dotnet-v3/issues/616 is pretty key to adoption for me too as there's lots of code I can't move forward without the equivalent of that facility. Happy to to/fro over there, or do a rebooted version of that issue which separates out the concerns about diagnostics and/or need for access to the _LeaseToken_ which that discusses which duplicates quite a lot of the above.

**Comment by ealsur** [comment] 2020-01-03 18:29
I'll try to address this, and the other issue, through the reinstatement of the Context (which provides LeaseToken + Raw Response for headers + Checkpoint). As I said, this might get moved to vNextdue to the contract change, and since vNext is already a breaking change in many aspects (see #1119 ), it would be the right place to do it.

**Comment by bartelink** [comment] 2020-01-03 18:41
That's wonderful to hear - I should be able to make the time to progress the integration as things drop as getting this onto the new stack is something I'm very concerned about. I'm also very hopeful of perf benefits of 1119 (and am ready for https://github.com/jet/propulsion to move to STJ as part of this). I can't envisage there being an issue with taking a vNext dep.

**Comment by bartelink** [comment] 2020-01-03 21:45
related: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/400

**Closed** 2021-04-02 19:11 UTC
Labels: ChangeFeed, feature-request
