### ISSUE TITLE
[Discussion]Address request honor user cancellation token

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-cosmos-dotnet-v3#3521] opened 2022-10-28 15:00 UTC
Currently, gateway address calls will not honor user cancellation token, re-examine whether we cancel it while not impacting address calls.

**Comment by ealsur** [comment] 2022-10-28 15:38
Already discussed on https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3279

**Comment by ealsur** [comment] 2022-10-28 17:47
Also related https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3284#discussion_r903162843

**Comment by ealsur** [comment] 2023-03-22 22:45
Closing as by design

**Closed by ealsur** 2023-03-22 22:45 UTC
Labels: improvement, .NET v3 SDK
