### ISSUE TITLE
FeedIterator<T>.ReadNextAsync throws NullReferenceException with custom serializer

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#871] opened 2019-10-02 15:28 UTC
**Describe the bug**
FeedIterator<T>.ReadNextAsync throws NullReferenceException with custom serializer.
The stream sent to the serializer is empty. `All the other Cosmos methos serialize fine and ```GetItemQueryStreamIterator``` works as does the default serializer.

**To Reproduce**
```
var families = new List<Family>();

var setIterator = container.GetItemQueryIterator<Family>(requestOptions: new QueryRequestOptions { MaxItemCount = 1 });
while (setIterator.HasMoreResults)
{
    foreach (var item in await setIterator.ReadNextAsync())
    {
        families.Add(item);
    }
}
```
**Expected behavior**
Deserialized object.

**Actual behavior**
NullReferenceException 

**Environment summary**
SDK Version: 3.0.100
Cosmos Version: 3.2.0
OS Version: Windows 10

**Comment by j82w** [comment] 2019-10-02 16:05
Can you please provide the full exception message?

Query does return empty pages. If you have a custom serializer it should be able to handle this.

**Comment by fuocor** [comment] 2019-10-02 16:14
I tracked it down, The FeedIterator wraps the result inside a response with a "Documents" element. The default serializer seems to address it whereas a custom serializer needs to drill into the response

**Comment by j82w** [comment] 2019-10-02 16:19
Here is what the [contract ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/345b91d51c6010eda52dc6c8ca42b145082bf1a3/Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElementSerializer.cs#L118)should look like.

```
            // The stream contract should return the same contract as read feed.
            // {
            //    "_rid": "qHVdAImeKAQ=",
            //    "Documents": [{
            //        "id": "03230",
            //        "_rid": "qHVdAImeKAQBAAAAAAAAAA==",
            //        "_self": "dbs\/qHVdAA==\/colls\/qHVdAImeKAQ=\/docs\/qHVdAImeKAQBAAAAAAAAAA==\/",
            //        "_etag": "\"410000b0-0000-0000-0000-597916b00000\"",
            //        "_attachments": "attachments\/",
            //        "_ts": 1501107886
            //    }],
            //    "_count": 1
            // }
```

**Comment by j82w** [comment] 2019-10-02 16:28
@fuocor I'm closing this issue since you figured out the issue. Please re-open it the issue isn't fixed.

**Comment by fuocor** [comment] 2019-10-02 16:30
It makes writing a custom serializer nearly impossible. The type requested from the serializer is ```CosmosFeedResponseUtil<T>```. How do you expect a custom serializer to instantiate that?

**Comment by j82w** [comment] 2019-10-02 16:40
That's a good point. The test have access to the internals which is why it's not having an issue with this.

The only option I see is to make `CosmosFeedResponseUtil<T>` public. Do you see any other alternatives?

**Comment by fuocor** [comment] 2019-10-02 16:47
Ask for an interface or abstract base class.

**Comment by fuocor** [comment] 2019-10-02 17:26
You have similar problems with ChangeFeed Processing. 
```
 ResponseMessage.EnsureSuccessStatusCode()
    CosmosResponseFactory.ToObjectInternal[T](ResponseMessage cosmosResponseMessage, CosmosSerializer jsonSerializer)
    CosmosResponseFactory.<CreateItemResponseAsync>b__6_0[T](ResponseMessage cosmosResponseMessage)
    CosmosResponseFactory.ProcessMessageAsync[T](Task`1 cosmosResponseTask, Func`2 createResponse)
    DocumentServiceLeaseStoreCosmos.MarkInitializedAsync()
    BootstrapperCore.InitializeAsync()
    BootstrapperCore.InitializeAsync()
    PartitionManagerCore.StartAsync()
    ChangeFeedProcessorCore`1.StartAsync()
```

**Comment by j82w** [comment] 2019-10-02 17:28
ResponseMessage and ItemResponse<T> are public. It shouldn't have any issue creating an instance of these.

**Comment by fuocor** [comment] 2019-10-02 17:41
It's the content of the response that is the problem ```DocumentServiceLeaseCore``` and ```LockDocument```

**Comment by j82w** [comment] 2019-10-03 11:33
DocumentServiceLeaseCore and LockDocument shouldn't be using the custom serializer. It should be using the property serializer. That's definitely a bug. Fixing that seems like it's going to be interesting.

**Comment by joshlang** [comment] 2019-11-19 16:44
FYI:  Using cosmos change feed is completely blocked for us until this is fixed.  We can't deserialize CosmosFeedResponseUtil.

**Comment by j82w** [comment] 2019-11-20 14:26
@ealsur  does PR #944  fix this issue?

**Comment by ealsur** [comment] 2019-11-20 15:41
Yes, it fixes using a custom serializer with Change Feed, as it will only used for the Delegate changes.

**Comment by j82w** [comment] 2019-11-20 15:52
We should be doing a release later this week or early next week. Just waiting on a few more PRs to get merged first.

**Comment by joshlang** [comment] 2019-11-20 15:54
That timeline will work for us.  Thanks!

**Closed** 2020-02-27 15:22 UTC
