### ISSUE TITLE
Custom handlers not executed from CreateItemQuery<T>()

### ISSUE THREAD

**Issue by lpunderscore** [Azure/azure-cosmos-dotnet-v3#93] opened 2019-03-26 17:44 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When using a custom "CosmosRequestHandler", the handler is not called when using CreateItemQuery<T>()

**To Reproduce**
Create a simple cosmosclient from the CosmosClientBuilder
Create a simple handler
Use the AddCustomHandlers() extension to add the handler

use ReadItemAsync<T> and see the handler execute.

var res = container.Items.CreateItemQuery<T>("query", "pk");

            while (res.HasMoreResults)
            {
                CosmosQueryResponse<T> results = await res.FetchNextSetAsync();
                foreach (T result in results)
                {
                    Console.WriteLine(result.Id);
                }
            }
Results are fetched, middleware never called.

**Expected behavior**
The middleware logic is executed

**Actual behavior**
The middleware is ignored

**Environment summary**
SDK Version: 3.0.0.9
OS Version (e.g. Windows, Linux, MacOSX)

**Comment by kentcb** [comment] 2019-03-27 00:27
Duplicate of #19 (and no, this still isn't fixed in `3.0.0.9-preview`).

**Comment by j82w** [comment] 2019-03-27 11:25
Hi @lpunderscore,

This is a known issue. I'm currently working on integrating query into the v3 pipeline. This will be done over multiple PRs over the next few weeks.

**Comment by j82w** [comment] 2019-04-01 21:06
Here is the first [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/99) to update the test so I can verify my next PR does not cause any regressions.

**Comment by j82w** [comment] 2019-04-10 18:27
Here is the [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/109) to update query to go to the handler pipeline.

**Comment by j82w** [comment] 2019-04-15 12:29
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/109

**Closed by j82w** 2019-04-15 12:29 UTC
