### ISSUE TITLE
ReadItemAsync -> Getting Unauthorized when using Gateway mode on id with # char despite getting NotFound when using Direct Mode

### ISSUE THREAD

**Issue by govenkat-ms** [Azure/azure-cosmos-dotnet-v3#1734] opened 2020-07-29 08:44 UTC
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Basically I have a test case which is validating some input string with invalid chars. These ids do not exist in the Cosmos DB instance and I expect the result to be NotFound. However, when using the **#** char anywhere in the id string and gateway mode I get the Unauthorized status code while in direct mode I get the expected NotFound status code.

**To Reproduce**
Here's some linq to reproduce.

```
var client = new 
		CosmosClientBuilder(connectionString)
		.WithConnectionModeGateway()
		.Build();
	
	var container = client.GetContainer("db", "computeStore");
	try {
		var obj = await container.ReadItemAsync<object>($"somename#", new PartitionKey("cb3917c3-2199-45f2-8eda-32feaedfb35a"));
	}
	catch (CosmosException ex)
	{
		$"{ex.StatusCode}".Dump();
	}
```

**Expected behavior**
I expected to get CosmosException with status code NotFound when searching on a non-existent document.

**Actual behavior**
Instead got Unauthorized in gateway mode even though the connection string is correct. In direct mode, I got the expected behavior of CosmosException with status code NotFound. This behavior was only exhibited on the # char.

**Environment summary**
SDK Version: 3.11.0
OS Version Windows

**Additional context**
Response status code does not indicate success: Unauthorized (401); Substatus: 0; ActivityId: dd4572f5-5bec-4762-a8d0-54a6ae457ab9; Reason: (The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'get
docs
dbs/db/colls/computeStore/docs/somename
wed, 29 jul 2020 08:42:37 gmt

**Comment by j82w** [comment] 2020-08-05 14:48
The problem is you are using [non-support characters](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet#remarks) in the id. We do have a backlog item to fix the service to handle this scenario, but we don't currently have a time frame.

**Comment by govenkat-ms** [comment] 2020-08-06 20:16
But why does it throw Unauthorized for unsupported characters?

**Comment by j82w** [comment] 2020-08-07 11:49
Authentication always happens first. The [authentication](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1a8e08721ec241a8cb96014bbdea61c457373556/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L6436) uses the URL which includes the id (`dbs/db1/colls/coll1/myItemId`) to create the authentication header. The gateway assumes that the URL is URL encoded so it decodes the URL and generates the authentication header and verifies the one in the request matches the one it generated locally. If you have a special character it causes the decoding to convert it the value making the authentication headers to not match and causing it throw the Unauthorized exception.

Example with happy scenario:
`My Id `-> URL encoded `My%20Id` -> URL decode `My Id`

Example when id has custom characters:
`My%20Id `-> URL encoded `My%20Id` -> URL decode `My Id`

Since this is not an issue with the SDK I'm going to close the issue. Here is a link of where you can leave feedback for the Cosmos DB service: https://feedback.azure.com/forums/263030-azure-cosmos-db

**Closed by j82w** 2020-08-07 11:49 UTC
