### ISSUE TITLE
Change feed processor not load balancing between multiple instances of webjob.

### ISSUE THREAD

**Issue by ravikumarmistry** [Azure/azure-cosmos-dotnet-v3#1853] opened 2020-09-16 11:30 UTC
**Describe the bug**
I have created a web job that is listening to the change feed but when I create multiple instances of the same web job only one instance is handling all the changes. 

**To Reproduce**
Following is the configuration I am using

```C
usersContainer
                .GetChangeFeedProcessorBuilder<UserDocument>("ChangeFeedProcessor", changeFeedHandler.Handler)
                    .WithInstanceName("instance-" + Guid.NewGuid())
                    .WithMaxItems(50)
                    .WithLeaseContainer(leaseContainer)
                    .Build();
```

**Expected behavior**
Users container has the partition Key as `/id`. It should load balance the change feed between multiple workers based on number of the partition.

**Actual behavior**
Only the first web job getting all the changes. All the other jobs sitting idle.

**Environment summary**
SDK Version: .Net core 3.1
OS Version (e.g. Windows, Linux, MacOSX) Windows 10

**Additional context**
Users container for change feed => partition Key `/id`

**Comment by bartelink** [comment] 2020-09-16 15:02
There need to be >1 physical partitions in your container for you to get concurrency ?

**Comment by ravikumarmistry** [comment] 2020-09-17 05:19
> There need to be >1 physical partitions in your container for you to get concurrency?

@bartelink But physical partitions is something cosmos DB manages and cosmos client does not have control over it. Does that mean that if due to some reason cosmos decide to put all the data to the same physical partition we cant scale-out the change feed?

**Comment by bartelink** [comment] 2020-09-17 06:30
Yup - but you can force splits by assigning more than 5k RU (either for an active container, in which case the split happens over the course of a few minutes, or you can create a fresh container with >1 node from the off)

**Comment by ravikumarmistry** [comment] 2020-09-17 15:40
> Yup - but you can force splits by assigning more than 5k RU (either for an active container, in which case the split happens over the course of a few minutes, or you can create a fresh container with >1 node from the off)

@bartelink  Can you please guide me to any documentation on it to understand it fully.

**Comment by ealsur** [comment] 2020-09-17 16:04
This is the same issue as https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1850, please see the answer there.

Change Feed consumption can only be parallelized at the physical partition level.

In any case, the question would be: Why do you need a higher level of parallelization? Is the machine's CPU at 100% while processing changes so you need multiple machines? If the answer is no, then adding more machines might not help, and having more leases won't have the impact you desire. If your concern is the processing speed, take a look at your handler implementation and analyze why it takes the time it takes, maybe it is calling some other service API and that service API is slow?

**Comment by ravikumarmistry** [comment] 2020-09-18 12:33
@ealsur The application I am working on is a multitenant application where each tenant has their own dedicated database. I have to perform some denormalization in cosmos DB based on the changes happening in a container for each database. I have a web job which is listening to 400 different database containers. But the number of the document which is processed for each change is about 200 to 300. So I was thinking of taking advantage of scaleout to distribute the load to multiple web jobs by creating multiple instances. But I see it is not that straight forword.

Can you suggest something which is scalable? And does not require to create infrastructure dynamically (e.g. dedicated function app for each tenant)

**Comment by ealsur** [comment] 2020-09-18 21:34
Like I mentioned, scale-out across multiple machine is useful in the event that the work you are doing is primarily CPU bound, because multiple instances offer you a higher CPU budget.

Change Feed can be read per container, so if you have multiple tenants where each tenant is a different database/container, then you are looking at 1 Change Feed Processor per tenant. You can distribute those Processors across multiple machines (assign a bucket of tenants to each machine and each machine will spin up 1 processor per assigned tenant). That's what I can think about with your current scenario.

**Comment by ealsur** [comment] 2020-09-21 17:55
Closing as expected behavior

**Closed by ealsur** 2020-09-21 17:55 UTC
Labels: ChangeFeed
